<?php

$lang = array (
	'apacserver' => 'Управління веб-сервером',
	'directory_password' => 'Встановлення пароля в каталозі',
	'apacserver_pass_selectdom' => 'Виберіть домен',
	'apacserver_pass_nodominacc' => 'Спочатку потрібно додати домен до облікового запису',
	'apacserver_dir_safe' => 'Каталог не існує або неправильний формат',
	'apacserver_pass_safe' => 'Слабкий пароль',
	'apacserver_add_dir_failed_already_exist' => 'Пароль на данну папку вже задано.',
	'apacserver_add_www_redir_ok' => 'Переадресацію успішно додано',
	'apacserver_delete_www_redir_ok' => 'Переадресація успішно видалена',
	'apacserver_add_www_failed_exist' => 'Цей тип переадресування вже існує.',
	'apacserver_add_www_failed_bad_from' => 'Недійсний формат назви сайту',
	'apacserver_add_www_failed_bad_to' => 'Недійсний формат значення',
	'apacserver_add_www_failed_not_perm' => 'Немає прав для цієї операції!',
	'apacserver_add_http_failed_exist' => 'Переадресація для цього сайту вже існує.',
	'apacserver_add_http_redir_ok' => 'Переадресацію успішно додано',
	'apacserver_delete_http_redir_ok' => 'Переадресація успішно видалена',
	
	'tpl_apac_delete' 	=> 'Вилучити',
	'msg_apac_ok' 		=> 'Успішно',
	'msg_apac_not_perm' 	=> 'Не выполнено',
	
	'tpl_apac_jmp_site' 	=> 'Переідресація сайтів',
	'tpl_apac_add_site' 	=> 'Додати сайт',
	'tpl_apac_site' 	=> 'Cайт',
	'tpl_apac_www' 		=> 'www',
	'tpl_apac_nowww' 	=> 'без www',
	'tpl_apac_both' 	=> 'обидва',
	'tpl_apac_pattern' 	=> 'По шаблону',
	'tpl_apac_destination' 	=> 'Призначення',
	'tpl_apac_add_jpm' 	=> 'Зачекайте, додається перенаправлення.... ',
	'tpl_apac_forwarding' 	=> 'Перенаправлення',
	'tpl_apac_forwarding_listhttp' 	=> 'Список перенаправлень',
	'tpl_apac_action_list' 	=> 'Сайт, Користувач, Призначення, Переадресація, Дія',
	
	'tpl_apac_user' 	=> 'Користувач',
	'tpl_apac_action' 	=> 'Дія',

	'tpl_apac_jmp_far' 	=> 'Переадресація HTTP — HTTPS',
	'tpl_apac_add_folder' 	=> 'Встановіть пароль на каталог',
	'tpl_apac_jmp_type' 	=> 'Тип переадресації',
	'tpl_apac_select_http' 	=> 'https в http',
	'tpl_apac_select_https' 	=> 'http в https',
	'tpl_apac_folders' 	=> 'Каталоги',
	'tpl_apac_folder' 	=> 'Каталог',
	'tpl_apac_action_list1' 	=> 'Сайт, Користувач, Переадресація, Дія',
	'tpl_apac_action_list2' 	=> 'Каталог, Користувач, Пароль, Дія',

	'tpl_apac_set_pass_folder' 	=> 'Встановлення пароля в каталозі',
	'tpl_apac_passwd' 	=> 'Пароль',
	'tpl_apac_nopass_folder' 	=> 'Жодна з папок не має пароля',

	'tpl_apac_select_www' 		=> 'в www.',
	'tpl_apac_select_nowww' 	=> 'в .',
	'tpl_apac_jmp_www' 	=> 'Переадресація WWW',


	'js_apac_jmp_table' 	=> 'Таблиця вже містить масову передачу для цього сайту.',
	'js_apac_add_domain' 	=> 'Необхідно додати домени до облікового запису',
	'apacserver_list_directory' 	=> 'Список запаролених каталогів',
	'apacserver_list_not_directory' 	=> 'Список запаролених каталогів пустий',
	'apacserver_list_http' 	=> 'Список доменів',
	'apacserver_none_list_http' 	=> 'Список доменів пустий',
	'apacserver_list_directory_http' 	=> 'Список Каталогів',	
	'apacserver_none_list_directory_http' 	=> 'Список Каталогів пустий',
	'apacserver_not_remove' 	=> 'Це не ваше',
	'apacserver_not_type' 	=> 'Не існуючий тип',
	'apacserver_list_forwarding' 	=> 'Список переадресацій',
	'apacserver_not_list_forwarding' 	=> 'Список переадресацій пустий',	
	'apacserver_not_unic_id' 	=> 'unic_id введено не правильно. Або це перенаправлення більше неіснує.',		
	'apacserver_not_domain' 	=> 'Не існуючий домен.',
	'apacserver_not_forward' 	=> 'Не правильно призначено переадресацію',
	'apacserver_not_path_forward' 	=> 'Не вказано шлях переадресації',	
	'apacserver_del_process' 	=> 'Видаляється...',

	'apacserver_setpass_login' 	=> 'Вхід',
	'apacserver_notset_any_redir_site' 	=> 'Не встановлено переадресації на жоден із сайтів.',
	'apacserver_notset_any_redir_http' 	=> 'Не встановлена HTTP переадресація на жоден із сайтів.',
	'apacserver_seluser' => 'Виберіть користувача',
	'apacserver_http_failedadd' => 'Помилка параметрів. Користувача не обрано. ',
	'apacserver_error_pages' => 'Сторінки помилок',
	'apacserver_list_error_pages' 	=> 'Свої сторінки помилок',
	'apacserver_error' 	=> 'помилка',
	'apacserver_code_error' 	=> 'Код помилки',	
	'apacserver_file' 	=> 'Розширення файлів',	
	'apacserver_fild_load' 	=> 'Поле для завантаження',
	'apacserver_download' 	=> 'Завантажити',
	'apacserver_visible_file' 	=> 'Подивитися',
	'apacserver_delete' 	=> 'Вилучити',
	'apacserver_save' 	=> 'Зберегти',	
	'apacserver_not_site' 	=> 'Користувач не має сайтів',	
	'apacserver_not_file_download' 	=> 'Не підтримується тип файлу',
	'apacserver_error_file_download' 	=> 'Помилка завантаження файлів',
	'apacserver_optimization' 	=> 'Оптимізація роботи сайту',	
	'apacserver_optimization_gzip' 	=> 'Увімкнути gzip стиснення',
	'apacserver_optimization_cesh' 	=> 'Увімкнути кешування статичних файлів в браузері',
	'apacserver_successfully' 	=> 'Зміни збережені',
	'apacserver_time_cash' 	=> 'Час кешування: ',
	'apacserver_day' 	=> 'днів',
	'apacserver_incorecly' 	=> 'Не правильне значення',
	'apacserver_optimisation_files' 	=> 'Оптимізувати файли',
	'apacserver_bacup_copy' 	=> 'Шлях для резервних копій',
	'apacserver_save_bacup_copy' 	=> 'Зберегти резервні копії',
	'apacserver_not_files_optimisation' 	=> 'Немає файлів для оптимізації',	
	'apacserver_error_directory' 	=> 'Каталог не відповідає регулярному виразу',		
	'apacserver_action' 	=> 'Дія',			
	'apacserver_action_restore' 	=> 'Відновити',	
	'apacserver_path' 	=> 'Каталог',		
	'apacserver_date' 	=> 'дата',
	'apacserver_error_id' 	=> 'Помилка id bacup',
	'apacserver_error_domain' 	=> 'Домен не відповідає регулярному виразу',	
	'apacserver_error_user' 	=> 'Користувач не відповідає регулярному виразу',
	'apacserver_restore_succesfully' 	=> 'Файли відновлені з резервних копій',	
	'apacserver_remove_succesfully' 	=> 'Резервні копії видалено',
	'apacserver_empty_path' 	=> 'Щоб створити резервні копії, вкажіть шлях.',
	'apacserver_empty_path_1' 	=> 'Для створення резервних копій вкажіть папку',

    'apacserver_wrongdest1' 	=> 'Недійсний формат призначення. Вкажіть у форматі без http.',
	'apacserver_gpagespeed_link_text' 	=> 'Перевірити в Google PageSpeed Insights',
    'apacserver_extCache' 	=> 'Розширення для кешування: ',
    'apacserver_extCacheEx' 	=> 'Вкажіть розширення через ; , | або пробіл. Наприклад: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',
    'apacserver_extCacheTimeMin' 	=> 'минут',
    'apacserver_extCacheTimeHour' 	=> 'годинн',

    'apacserver_cacheHintWrongExt' => 'Список розширень у неправильному форматі.',
    'apacserver_cacheHintWrongExtExp' => 'Час кешування вказаний у неправильному форматі',
    'apacserver_cacheHintSaveok' => 'Збережено успішно',
    'apacserver_cacheWaitPlease' => 'Будь ласка зачекайте',
    'apacserver_dostatforthisext' => 'Обробляти статику через nginx для ци розширень',
    'apacserver_error_reserv_directory' => 'Помилка. Каталог зарезервовано системою.',
    'apacserver_error_type_files' => '<br>Підтримується типи файлів html, htm, php',
    'apacserver_optimization_off_nginx' => 'Вимкнути кешування динаміки nginx',
    'apacserver_empty_ssl_domain' => 'Помилка переадресації. На домен не встановлений ssl сертифікат.',
    'apacserver_addredir' => 'Додати перенаправлення',
    'apacserver_optimiz_title' => 'Оптимізація',
    'apacserver_addpasstitle' => 'Додати пароль',
	'apacserver_extCacheEx_1' 	=> 'Список часто використовуваних розширень: ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff|woff2',	
	
	
);