<?php
$lang = array (
	'blacklist' => 'Чорні списки ip',
	'blacklist_ip' => 'ip для перевірки',
	'blacklist_check' => 'Перевірити',
	'blacklist_save' => 'Зберегти',
	'blacklist_error_domain' => 'Вказаний домен не підходить для регулярного виразу',	
	'blacklist_succesfully' => 'Успішно завершено.',	
	'blacklist_error_ip' => 'ip адреса введена неправильно або порожня',
	'blacklist_dnsbl_server' => 'DNSBL сервер',	
	'blacklist_status' => 'Статус',	
	'blacklist_black' => 'В чорному списку',
	'blacklist_ok' => 'Не в чорному списку',
	'blacklist_detail' => 'Додаткова інформація',
	'blacklist_list_dnsbl' => 'Список DNSBL серверів',	
	'blacklist_check_ip_dnsbl' => 'Перевірка IP у чорних списках',
	'blacklist_monitor' => 'Моніторинг по часу локальні ip',	
	'blacklist_period_minutes' => 'Період хвилин',
	'blacklist_error_minutes' => 'Хвилини введено неправильно.',
	'blacklist_many_minutes' => 'Дуже багато хвилин',	
	'blacklist_disabled_scan' => 'Сканування вимкнено',	
	'blacklist_whait_scan' => 'Зачекайте, триває сканування',
	'blacklist_whait_save' => 'Зачекайте, триває збереження',
	'blacklist_block_ip' => 'Заблоковані ip',
    'blacklist_check_ip_header' => 'Перевірити ip',
    'blacklist_resultcheck' => 'Результати перевірки',
);
