<?php

$lang = array(
    'certs_control' => 'Управління SSL/TLS',
    'service_serv' => 'Сервіси',
    'service_domain' => 'Домени',
    'service_expire' => 'Термін',
    'service_expire_up' => 'Термін дії до',
    'service_keysize' => 'Розмір ключа',
    'service_issuer' => 'Видавець',
    'service_action' => 'Дії',
    'service_action_loadnewcert' => 'Завантажити новий',
    'service_apply_exist' => 'Застосувати існуючий сертифікат',
    'service_install_newcert' => 'Встановити новий сертифікат',
    'service_install_newcert_title' => 'Виберіть один або кілька сервісів для встановлення сертифіката',
    'service_certificate' => 'Сертифікат',
    'service_privatekey' => 'Приватний ключ',
    'service_cabunlde' => 'Certificate Authority Bundle',
    'service_reinstall_cert' => 'Встановити новий сертифікат',
    'service_install_error_nosel' => 'Виберіть сервіс, для якого потрібно встановити сертифікат',
    'service_applyexist' => 'Застосувати існуючий сертифікат',
    'service_applyexist_ok' => 'Застосовано успішно',
    'service_install_new_ok' => 'Новий сертифікат встановлений успішно',
    'service_save' => 'Зберегти',
    'service_cancel' => 'Скасувати',
    'service_cert_del' => 'Видалити сертифікат',
    'service_overwrite_cert_q' => 'Перезаписати сертифікат?',
    'service_overwrite_cert_yes' => 'Так',
    'service_overwrite_cert_no' => 'Ні',
    'service_cert_not_ins' => 'Сертифікат не встановлено',
    'service_cert_del_confirm' => 'Підтвердіть видалення сертифіката',
    'service_cert_del_confirm_yes' => 'Так',
    'service_cert_del_confirm_no' => 'Ні',
    'service_cert_del_complete' => 'Сертифікат видалено',
    'service_cert_view' => 'Переглянути сертифікат',
    
    'service_cert_install_wrong_cert' => 'Сертифікат не встановлений, перевірте коректність введеного сертифіката, ключа та Authority Bundle',
    
    
    'tpl_certs_cert' => 'Сертифікат',
    'tpl_certs_del' => 'Видалити',
    'tpl_certs_certdel' => 'Видалити сертифікат',
    'tpl_certs_cerdeactiv' => 'Деактивувати сертифікат',
    'tpl_certs_key' => 'Ключ',
    'tpl_certs_certkey' => 'Видалити ключ',
    'tpl_certs_gen_csr' => 'Створити CSR',
    'tpl_certs_select_key' => 'Виберіть ключ',
    'tpl_certs_key_new' => 'Новий ключ',
    'tpl_certs_domain_name' => 'Ім`я домену',
    'tpl_certs_key_size' => 'Виберіть розмір',
    
    'tpl_certs_country' => 'Країна',
    'tpl_certs_state' => 'Штат',
    'tpl_certs_city' => 'Місто',
    'tpl_certs_company' => 'Компанія',
    'tpl_certs_division' => 'Відділ',
    'tpl_certs_create_csr' => 'Створити CSR',
    'tpl_certs_load_crt' => 'Завантажити сертифікат',
    'tpl_certs_name' => 'Ім`я',
    'tpl_certs_copy_file_crt' => 'Скопіюйте файл сертифіката',
    'tpl_certs_insert_file_crt' => 'Вставте файл сертифіката',
    'tpl_certs_download_crt' => 'Завантажити CRT',
    'tpl_certs_your_crt' => 'Ваші CRT', 

    
    'tpl_certs_domain' => 'Домен',
    'tpl_certs_certs' => 'Сертифікат',
    'tpl_certs_lenkey' => 'Довжина ключа',
    'tpl_certs_status' => 'Статус',
    'tpl_certs_func' => 'Функції',
    'tpl_certs_edit' => 'Редагувати',
    'tpl_certs_save' => 'Зберегти',
    'tpl_certs_del_key' => 'Видалити ключ',
    
    'tpl_certs_c_keys' => 'Ключі',
    'tpl_certs_c_crts' => 'Сертифікати',
    'tpl_certs_c_setting_crts' => 'Установка сертифіката',
    'tpl_certs_c_list_keycerts' => 'Список доменів та сертифікатів',
    'tpl_certs_c_create_priv_key' => 'Створити приватний ключ',
    'tpl_certs_c_name' => 'Ім`я',
    'tpl_certs_c_key_size' => 'Виберіть розмір',
    'tpl_certs_c_create_key' => 'Створити ключ',
    'tpl_certs_c_download_priv_key' => 'Завантажити приватний ключ',
    'tpl_certs_c_copy_key' => 'Скопіюйте ключ',
    'tpl_certs_c_insert_file_key' => 'Вставте файл із ключем',
    'tpl_certs_c_load_key' => 'Завантажити ключ',
    'tpl_certs_c_your_private_keys' => 'Ваші закриті ключі',
    
    'tpl_certs_c_generate_csr' => 'Створити CSR',
    'tpl_certs_c_select_key' => 'Виберіть ключ',
    'tpl_certs_c_new' => 'Новий',
    'tpl_certs_c_name_domain' => 'Ім`я домену',
    'tpl_certs_c_select_size' => 'Виберіть розмір',
    
    'tpl_certs_c_install_cert' => 'Встановити сертифікат',
    'tpl_certs_c_select_domain' => 'Виберіть домен',
    'tpl_certs_c_select_crt' => 'Виберіть сертифікат',
    'tpl_certs_c_or_load_new' => 'Або завантажте нижче',
    'tpl_certs_c_cert1' => 'Сертифікат (CRT)',
    'tpl_certs_key1' => 'Закритий ключ (KEY)',
    'tpl_certs_c_list_domain_crts' => 'Список доменів та сертифікатів',
    
    'tpl_certs_s_domain_name' => 'Домове ім`я',
    'tpl_certs_s_ip_addr' => 'IP адреса',
    'tpl_certs_s_root_dir' => 'Корнева директорія',
    'tpl_certs_s_owner' => 'Власник',
    'tpl_certs_s_key_size' => 'Розмір ключа',
    'tpl_certs_s_domain_def' => 'Домен за замовчуванням',
    'tpl_certs_s_action' => 'Дія',
    'tpl_certs_s_domain_def_ip' => 'Встановити домен за замовчуванням на IP',
    
    'tpl_certs_s_service_cert' => 'Сертифікати сервісів',
    'tpl_certs_s_list_certs' => 'Список сертифікатів',
    

    'msg_cert_err_nodomain' => 'Помилка.Відсутнє ім`я домену',
    'msg_cert_err_nocode' => 'Помилка. Код країни повинен містити два символи. Наприклад, UK',
    'msg_cert_err_State' => 'Помилка. Штат має бути заповнений у форматі a-z.',
    'msg_cert_errCity' => 'Помилка. Місто має бути заповнене у форматі a-z.',
    'msg_cert_errCompany' => 'Помилка. Компанія має бути заповнена у форматі a-z.',
    'msg_cert_errOtdel' => 'Помилка. Відділ має бути заповнений у форматі a-z.',
    
    'msg_cert_create_info0' => 'Сертифікат для',
    'msg_cert_create_info1' => 'вдало створено',
    'msg_cert_err_create_domain' => 'Помилка. Виникла проблема під час завантаження ключа для цього домену.',
    'msg_cert_err_del_cert' => 'Помилка. Ваш ключ не можна видалити, тому що він використовується в хості',
    'msg_cert_err_del_cert_cert' => 'Помилка. Ваш сертифікат не можна видалити, тому що він використовується в хості',
    'msg_cert_ok_del_cert' => 'Ключ та його сертифікат були успішно видалені.',
    'msg_cert_ok_del_cert1' => 'Сертифікат видалено',
    'msg_cert_err_load_certs' => 'Помилка. Сертифікат не завантажено',
    'msg_cert_let_info0' => 'Сертифікат для',
    'msg_cert_let_info1' => 'конфігурований і застосований',
    
    'msg_cert_ok_unset_dom' => 'Сертифікат був прибраний з домену',
    'msg_cert_apply_lets_cert' => 'Зачекайте, будь ласка. Йде процес створення сертифіката',
    
    'msg_cert_installed_ok' => 'Сертифікат встановлено',
    
    'msg_cert_not_installed_yet' => 'Сертифікат не встановлений',
    'msg_key_not_installed_yet' => 'Ключ не встановлений',
    'msg_cert_install_foremail' => 'Встановити сертифікат для пошти',
    'msg_cert_used_foremail' => 'Використовується для пошти',
    
    'msg_cert_generate_cert' => 'Створити сертифікат',
    
    'msg_cert_nocertkey' => 'Немає такого ключа та сертифіката, нічого видаляти.',
    
    'certs_control_gen_process' => 'Генерується...',
    'certs_control_apply_cert_process' => 'Застосовується...',
    'certs_control_remove_cert_process' => 'Видаляється...',
    'certs_control_install_newcert_process' => 'Встановлюється...',
    
    
    'certs_control_error_validcert' => 'Помилка. Ключ не відповідає цьому сертифікату',
    'certs_control_error_validcert_chain' => 'Помилка. Certificate Authority Bundle не відповідає цьому сертифікату',
    
    'certs_control_failed_gen_letsen' => 'Помилка створення сертифіката. Домен має бути прив`язаний!',
    'certs_control_failed_gen_letsen_dns_record' => 'Помилка створення сертифіката. Перевірте наявність днс запису на домен ',
    'certs_control_failed_gen_letsen_dns_record_error_arg' => 'Помилка створення сертифіката. Встановлено невідомий аргумент ',
    'certs_control_failed_gen_letsen_dns_record_AAAA' => 'Помилка створення сертифіката. У панелі немає віртуального хоста з ipv6 , Видаліть днс запис АААА ',
    'certs_control_failed_gen_letsen_serv' => 'Помилка створення сертифіката. Серверний хостнейм повинен бути прив`язаний до сервера айпі!',
    'certs_control_failed_gen_letsen_domain' => 'Помилка створення сертифіката. Домен повинен бути прив`язаний до IP-сервера. Перевірте днс запису на домен ',
    'certs_control_failed_gen_letsen_error_domain' => 'Помилка створення сертифіката. На даний домен заборонено видачу сертифіката ', 

    
    'certs_control_certload_ok' => 'Сертифікат успішно завантажено',
    'certs_control_keyload_ok' => 'Ключ успішно завантажений',
    
    'certs_control_certload_failedname' => 'Сертифікат не завантажено. Помилка імені сертифіката.',
    'certs_control_keyload_failedname' => 'Ключ не завантажений. Помилка імені ключа.',
    
    'certs_control_certload_wrongformat' => 'Невірний формат сертифіката.',
    'certs_control_keyload_wrongformat' => 'Неправильний формат ключа.',
    'msg_certs_control_certs_info0' => 'Сертифікат',
    'msg_certs_control_certs_info1' => 'успішно застосований',
    'cert_control_seluser' => 'Ім`я користувача',
    'cert_control_load_wait' => 'Будь ласка, зачекайте',
    'cert_control_gen_lets' => 'Згенерувати Lets Encrypt',
    'cert_control_gen_lets_renew' => 'Створити новий Lets Encrypt сертифікат',
    'cert_control_letsen_autorenew' => 'Автогенерація сертифіката',
    'cert_control_letsen_autorenew_stat_save' => 'Збережено',
    'certs_control_domain_setdef' => 'Домен встановлено на IP за замовчуванням',
    'certs_control_ipdomain' => 'IP адреса',
    'certs_control_gen_letsen_hostname_ok' => 'Сертифікат Lets Encrypt успішно згенерований',
    'certs_control_active_autorenew_lets_hostname' => 'Автогенерація сертифіката',
    'certs_control_no_keys' => 'Немає ключів',
    'certs_control_no_certs' => 'Немає сертифікатів',
    'certs_control_no_domains' => 'Немає доданих доменів',
    'certs_control_no_cert' => 'Прибрати сертифікат',
    'certs_control_gennew_letsen' => 'Створити новий Lets Encrypt',
    
    'certs_control_nottimeyet' => 'Сертифікат для',
    'certs_control_nottimeyet2' => 'ще актуальний',
    'certs_control_pleasereloadpage' => 'Сертифікат для сервісу brainy буде використаний через 20 секунд. Будь ласка, перезавантажте сторінку для відновлення роботи.',
    'certs_control_pleasereloadpage_del' => 'Сертифікат сервісу brainy буде видалений через 20 секунд. Будь ласка, перезавантажте сторінку для відновлення роботи.',
    
    'certs_control_pleasewaitloadinfocert' => 'Зачекайте, будь ласка. Завантажується інформація про сертифікат.',
    'certs_control_letsfailedexistgen' => 'Сертифікат ще не закінчився, тому неможливо створити новий сертифікат для домену ',
    
    'certs_warn_notinstall_certbot' => 'CertBOT не встановлено. Встановіть CertBOT.',
    'certs_warn_notinstall_certbot_btn' => 'Встановити CertBOT',
    'certs_warn_nothing_sel' => 'Будь ласка, виберіть сертифікат.',
    
    'certslets_tip_help' => 'Для створення Lets Encrypt сертифіката буде використаний хостнейм сервера. Ви можете змінити хостнейм у розділі <a target=_blank href=/index.php?do=properties>Налаштування сервера</a>. <br/>Будь ласка, переконайтесь у прив`язці до вашого сервера хостнейму ',
    
    'certs_error_nxdomaingencertlets' => 'Необхідно додати А запис з сервера айпи для домену ',
    'certs_error_genletssuffauth' => 'Недостатньо прав для авторизації домену',
    'certs_error_genletssuffauth_check' => 'Перевірте, що домен прив`язаний саме до цього сервера.',
    'certs_check_gencertforpanel_host' => 'Генерувати сертифікат для panel.hostname',
    'certs_check_gencertforpanel_host_hint' => 'Для створення сертифіката переконайтеся, що до вашого сервера прив`язаний домен panel.',
    'certs_select_cert' => 'Вибрати сертифікат',
    'certs_data_cert' => 'Дані сертифіката',
    'certs_too_many_cert' => 'Створіть сертифікат трохи пізніше. Вичерпано ліміт генерації сертифікатів.',
    'certs_too_many_cert_services' => 'Згенеруйте сертифікат сервісу трохи пізніше. Вичерпано ліміт генерації сертифікатів.',
    'certs_too_many_error' => 'Помилка створення сертифіката. Занадто багато невдалих створінь сертифікату. Перевірте конфігурації сайту на редиректи та повторіть спробу через кілька годин.',
    'certsfailedGenUnauth' => 'Помилка авторизації. Будь ласка, перевірте, чи не встановлено переадресацію в налаштуваннях сайту, пароль на авторизацію в кореневу директорію домену ',
    'certs_error_user' => 'Помилка користувача.',
    'certs_error_domain' => 'Помилка домену.',
    'certs_remove_domain_default_ip' => 'Видалити домен за замовчуванням на IP',
    'certs_wildcard' => 'Wildcard',
    'certs_wildcard_text' => 'Wildcard - можливість створення сертифіката виду: ',
    'certs_error_api_cloudflare' => 'Сайт підключений до cloudflare, виявлено помилку перевірки даних від сервісу cloudflare. Перевірте дані від cloudflare, а також ns сервера на домен.', 
    'certs_gencerttitle' => 'Генерація сертифіката',
    'certs_certdomaccpanel' => 'Сертифікат для домену, за яким доступна панель:',
    'certs_thiscertnotallow' => 'Це сертифікат не може бути згенерований разом з іншими. Тому сертифікати недоступні при його генерації.',
    'certs_limitslets' => 'Обмеження Lets Encrypt',
    'certs_control_cloudflare' =>' Якщо домен підключений з сервісу cloudfare, відключіть проксіювання, або додайте ваш домен через меню cloudflare, в панелі.',
    'certs_control_remove_cert_service' =>'Підтвердіть видалення сертифіката сервісу.<br><br> ПОПЕРЕДЖЕННЯ, видалення сертифіката сервісу призведе до подальшої зупинки сервісу, рекомендується перевстановити сертифікат або застосувати існуючий.',
    'certs_control_api_empty_user' => 'Такий користувач відсутній в ISP-панелі:',
    'certs_control_api_get_user_certs' => 'Список сертифікатів був успішно отриманий для користувача',
    'certs_control_api_error_parametrs' => 'Помилка в блоці параметрів',
    'certs_control_api_error_rm_cert' => 'Необхідний сертифікат не може бути видалений, оскільки він використовується',
    'certs_control_api_success_rm_cert' => 'Ключ та сертифікат були успішно видалені для користувача',
    'certs_control_api_empty_domain' => 'Не знайдено домену',
    'certs_control_get_log_letcen' => 'Дивитись лог Lets Encrypt',
    'certs_control_filed_crt' => 'Помилка генерації сертифіката',
    'certs_control_empty_log_letcen' => 'Не знайдено файл лога.',
);
