<?php

$lang = array(

	"access_denied" => "У Вас недостатньо прав для доступу до данного розділу",
	"access_deniedtitle" => "Доступ заборонено",
	"index" => "Головна сторінка",
	"input" => "Вхід",
	"login" => "Логін",
	"logout" => "Вихід",
	"password" => "Пароль",
	"ip_manager" => "IP менеджер",
	"ipmanager" => "IP менеджер",
	"memmanager" => "Менеджер ресурсів",
	"login_form" => "Форма входу",
	"navigation" => "Навігация",
	"ip_list" => "Список IP",
	"send" => "Відправити",
	"add" => "Додати",
	"delete" => "Видалити",
	"add_time" => "Тимчасово додати",
	"mysql" => "MySQL",
	"plans" => "Тарифи",
	"plan" => "Тариф",
	"new_plan" => "Новий тариф",
	"planname" => "Імя тарифу",
	"plan_properties" => "Властивості тарифа",
	"host_accounts" => "Хост-акаунти",
	"host_account" => "Хост-аккаунт",
	"quota" => "Квота",
	"yes" => "Так",
	"no" => "Ні",
	"change" => "Змінити",
	"install" => "Встановити",
	"reinstall" => "Перевстановити",
	"restart" => "Перезавантажити",
	"force_restart" => "Примусово перезавантажити",
	"start" => "Запустити",
	"stop" => "Зупинити",
	"controls" => "Керування",
	"edit" => "Редагувати",
	"edit_plain" => "Редагувати як текст",
	"set" => "Встановити",
	"update" => "Оновити",
	"version" => "Версія",
	"current_version" => "Теперішня версія",
	"add_user" => "Додати користувача",
	"add_db" => "Додати базу даних",
	"name" => "Імя",
	"add_user_to_db" => "Додати користувача в базу даних",
	"user" => "Користувач",
	"db" => "База даних",
	"exist_users" => "Існуючі користувачі",
	"exist_dbs" => "Існуючі бази даних",
	"privileges" => "Привілеї",
	"data" => "Данні",
	"structure" => "Структура",
	"default_mycnf" => "Відновити стандартний my.cnf",
	"change_root_pass" => "Змінити пароль root",
	"server_control" => "Керування сервером",
	"complectation" => "Комплектація",
	"php_install" => "Встановлення php",
	"apache_install" => "Встановлення apache",
	"apache_control" => "Керування apache",
	"change_passwords" => "Змінити паролі",
	"nginx_install" => "Встановлення nginx",
	"autostatic" => "Проксувати статику",
	"nginx_control" => "Керування nginx",
	"server_install" => "Встановлення сервера",
	"server_complectation" => "Комплектація сервера",
	"edit_apacheconf" => "Редагувати конфігурацію apache",
	"edit_nginxconf" => "Редагувати конфигурацію nginx",
	"add_site" => "Додати сайт",
	"site" => "Сайт",
	"site_name" => "Імя сайту",


	"site_alias" => "Псевдонім сайту",
	"site_admin" => "Адміністратор сайту",
	"site_root" => "Коренева папка сайту",
	"default_conf" => "Відновити стандартну конфігурацію",
	"email" => "Email",
	"ip" => "IP",
	"domain" => "Домен",
	"aliases" => "Аліаси",
	"dir" => "Каталог",
	"reload_hosts" => "Перезібрати віртуальні хости",
	"remove_host" => "Вилучити віртуальний хост",
	"current_complectation" => "Поточне обладнання",
	"basedir" => "Базовий каталог",
	"enter" => "Увійти",
	"options" => "Параметри",
	"please_wait" => "Будь ласка зачекайте",
	"processing" => "Триває процес.Будь ласка зачекайте",
	"deleting" => "Видаляється...",
	"access_error" => "помилка доступу",

	"topinfo_count_sites" => "Сайтів",
	"topinfo_ftp" => "FTP акаунтів",
	"topinfo_bandwidth" => "Трафік",
	"topinfo_databases" => "Баз",
	"topinfo_emailboxes" => "Скриньок",
	"topinfo_mailperhour" => "Листів в годину",
	"topinfo_plan" => "Тариф",
	"topinfo_disk" => "Місце",
	"topinfo_ip" => "IP",
	"topinfo_shell_access" => "Shell",
	"topinfo_language" => "Мова",
	"topinfo_username" => "Логін",
	"topinfo_rootdir" => "Домашній каталог",
	"topinfo_group" => "Група",
	"topinfo_clamav" => "Clamav",
	"topinfo_exim" => "Exim",
	"topinfo_dovecot" => "Dovecot",
	"topinfo_postfix" => "Postfix",
	"topinfo_webserver" => "webserver",
	"topinfo_cron" => "Cron",
	"topinfo_db" => "db",
	"topinfo_named" => "Named",
	"topinfo_loadavg" => "Load_AVG",
	"topinfo_diskspace" => "Disk",
	"topinfo_proftpd" => "FTP",
	"topinfo_pureftpd" => "FTP",
	"topinfo_brainy" => "Brainy",
	"topinfo_opendkim" => "OpenDKIM",
	"topinfo_brainysqld" => "BrainySQL",
	"topinfo_postgresql" => "PostgreSQL",
	"topinfo_fail2ban" => "fail2ban",

	"topinfo_g_nginx" => "Nginx",

	"topinfo_csf" => "CSF",
	"topinfo_spamassassin" => "SpamAssassin",

	"topinfo_saveok" => "Успішно збережено",
	"common_seluserplease" => "Виберіть користувача",
	"common_user_notselect" => "Користувача не вибрано",
	"nothing_found" => "Нічого не знайдено",
	"search_is_runnig" => "Пошук триває",
	"common_notselect" => "Не вибрано",
	"common_putname_label" => "Введіть ім`я",
	"common_user_current" => "Поточний користувач",
	"common_value_unlim" => "Необмежено",
	"main_title" => "BrainyCP — Панель керування сервером",
	"post_title" => " — BrainyCP",

	"min" => "мин.",

	"topinfo_tip" => "Дані оновлюються у фоновому режимі",
	"topinfo_tip_one" => "кожну",
	"topinfo_tip_not_one" => "кожні",

	"common_killall_ok" => "Процес зупинено примусово",

	"upload_caption" => "Файл не вибрано",
	"upload_btn_text" => "виберіть файл",

	"common_pagegencountonpage" => "Кількість на сторінці: ",

	"navigate_header_list" => "Розділи за категоріями",
	"navigate_header_tile" => "Всі розділи",

	"context_menu_password" => "Встановити пароль на каталог",
	"context_menu_optimization" => "Прискорення сайту",
	"context_menu_www" => "Увімкнути перенаправлення",
	"context_menu_certs_control" => "Встановити сертифікат SSL",
	"context_menu_certs_control_lets" => "Встановити Lets Encrypt сертифікат",
	"context_menu_http" => "Налаштувати HTTPS переадресацію",
	"context_menu_server_control_1" => "Змінити директиви PHP",
	"context_menu_openfolder" => "Керування файлами в менеджері файлів",
	"context_menu_antivirus" => "Перевірити сайт антивірусом",
	"context_menu_logging" => "Логи",
	"context_menu_web_statistics" => "Статистика",
	"context_menu_webserver_config" => "Доналаштувати віртуальні хости",
	"context_menu_mailforward" => "Налаштування пересилання пошти",
	"context_menu_spf" => "Керування SPF",
	"context_menu_opendkim" => "Керування DKIM",
	"context_menu_mail_antivirus" => "Перевірити папку пошти антивірусом",
	"context_menu_mail_statistic" => "Поштова статистика",
	"context_menu_mail_filter" => "Додати фільтр",
	"auth_title" => "BrainyCP — Сторінка авторизації",

	"common_config_monitor" => "Налаштувати",
	"common_config_updatecaption" => "Оновлення: ",
    "common_inhour"=>"о",
	"common_every1hour"=>"кожну",
    "common_every2to24"=>"кожних",
    "common_hour1hour"=>"годину",
    "common_hour2to4"=>"години",
    "common_hour5to24"=>"годин",

    "common_every1minute"=>"кожну",
    "common_every2to60"=>"кожні",
    "common_minute1hour"=>"хвилину",
    "common_minute2to4"=>"хвилини",
    "common_minute5to60and0"=>"хвилин",
    "common_everyhoursend"=>"кожної години",

	"gen_pass" => "Створіть пароль",
	"difficult_pass" => "Складність",

	"common_demo_version" => "Панель працює в режимі демонстрації. Менеджер файлів працює лише в режимі читання.",
	"common_demo_message" => "На жаль, в демонстраційній версії ця дія вимкнена.",

	"choose_file" => "виберіть файл",
	"no_file" => "Файл не обрано",

	"child_human_log_mysqldb" => "Створення резервної копії бази даних ",
	"child_human_log_preparelog1" => "Підготовка користувацьких файлів. ",
	"child_human_log_preparelog2" => "Копіювання файлів. ",
	"child_human_log_preparelog3" => "Створення необхідних каталогів. ",
	"child_human_log_process" => " ",
	"child_human_log_data_backup" => "Записування інформації про резервну копію. ",
	"child_human_log_remove_temp" => "Видалення тимчасових файлів. ",
	"child_human_log_finish_oper" => "Завершуючі дії. ",
	"child_human_log_finish_emailsendcomplete" => "Надсилання електронної пошти, якщо встановлено. ",
	"child_human_log_finish_calcbackupsfordelete" => "Розрахунок кількості резервних копій.",
	"child_human_log_finish_completecreatebackup" => "Процес резервного копіювання успішно завершено.",
	"child_human_log_startcreate_backup" => "Початок створення резервних копій. Користувач ",
	"child_human_log_uptodrop" => "Резервне копіювання на Dropbox. ",
	"child_human_log_uptogdrive" => "Резервне копіювання на GoogleDrive. ",
	"child_human_log_yadisk_putfile" => "Резервне копіювання на YandexDisk. ",
	"child_human_log_ftp" => "Резервне копіювання на FTP. ",

	"child_human_log_uptodrop_rest" => "Завантаження резервної копії з Dropbox. ",
	"child_human_log_uptogdrive_rest" => "Завантаження резервної копії з GoogleDrive. ",
	"child_human_log_yadisk_putfile_rest" => "Завантаження резервної копії з YandexDisk. ",
	"child_human_log_ftp_rest" => "Завантаження резервної копії з FTP. ",


	"child_human_logtrans_start" => "Початок переносу облікового запису.",
	"child_human_logtrans_transuser" => "Перенос користувача ",
	"child_human_logtrans_transuserend" => "Завершення переносу користувача ",
	"child_human_logtrans_restoreuser" => "Відновлення користувача.",
	"child_human_logtrans_restoredbuser" => "Відновлення користувачів баз даних користувача.",
	"child_human_logtrans_restoredbuserdbs" => "Відновлення баз даних коритувача.",
	"child_human_logtrans_autoins_backup" => "Відновлення списку встановлених CMS користувача.",
	"child_human_logtrans_restore_backups_jobs" => "Відновлення списка завдань резервного копіювання користувача.",

	"child_human_logtrans_restore_restoreftpacc" => "Відновлення ФТП акаунтів користувача.",
	"child_human_logtrans_restore_restorevhosts" => "Відновлення віртуальних хостів користувача.",
	"child_human_logtrans_restore_change_ips_domains" => "Зміна IP віртуальних хостів користувача.",
	"child_human_logtrans_restore_vhostsrebuild" => "Переналаштування віртуальних хостів користувача.",
	"child_human_logtrans_restore_addzones" => "Додавання ДНС зон користувача.",
	"child_human_logtrans_restore_restore_emails_user" => "Відновлення поштових акаунтів.",
	"child_human_logtrans_restore_restore_emails_routes" => "Відновлення маршрутизації пошти.",
	"child_human_logtrans_restore_email_forward" => "Відновлення поштових перенаправлень.",
	"child_human_logtrans_restorequalifyDomainJail" => "Відновлення qualifydomain для jail користувачів",
	"child_human_logtrans_restore_dns_user" => "Відновлення необхідних файлів.",
	"child_human_logtrans_restore_dkimkeys_user" => "Відновлення ключів DKIM.",
	"child_human_logtrans_restore_webserver_includes_user" => "Відновлення налаштувань віртуальних хостів.",
	"child_human_logtrans_restore_passdir_user" => "Відновлення налаштувань користувача.",
	"child_human_logtrans_restore_httpredir_user" => "Відновлення HTTP переадресації.",
	"child_human_logtrans_restore_siteredir_user" => "Відновлення переадресації сайту.",
	"child_human_logtrans_restore_opti_user" => "Відновлення налаштувань оптимізації сайтів.",
	"child_human_logtrans_crontab" => "Відновлення CRON завдань користувача.",

	"child_human_logtrans_restorebackuphint" => "Почато відновлення користувача ",
	"child_human_logtrans_restorebackuphintend" => "Завершено відновлення користувача ",
	"child_human_logtrans_clearuserdata" => "Видалення поточного користувача перед відновленням",

	"child_human_logtrans_userexist" => "Користувач з цим ім`ям вже існує ",

	"child_human_dns_type_cluster" => "Тип синхронізації: кластер",
	"child_human_dns_type_server" => "Тип синхронізації: сервер",
	"child_human_dns_ipaddress" => "IP адрес синхронізації: ",
	"child_human_dns_typeserver" => "Тип сервера: ",
	"child_human_backup_prepare" => "Виконання запиту...",

	"common_wrongname_pass" => "Неправильний логін або пароль",

	"child_human_backup_control_sum" => "Підрахунок контрольної суми резервної копії",
	"child_human_backup_logtrans" => "Лог: ",
	"child_human_backup_logtrans_ok" => "Резервна копія успішно збережена",

	"common_autoloadservice_after_reset_server" => "Автозапуск служби після перезапуску сервера",
	"common_autoloadservice_title" => "Автозавантаження",

	"child_human_hostaccsetjailhost" => "Відновлення налаштувань jail середовища користувача.",
	"child_human_hostaccsetjailphp" => "Відновлення налаштувань jail php користувача.",
	"child_human_backup_opensslcrypt" => "Шифрування/дешифрування бекапу",
	"child_human_backup_openssldecryptFailed" => "Розшифрування закінчилася помилкою. Відновлення перервано. Зміни не внесено.",

	"child_human_hostaccJaillOffBeforeRestore" => "Відновлення користувача.",
	"child_human_hostaccRestoreContinue" => "Копіювання файлів.",

	"current_lang" => "Українська",

	"child_human_listDBrestoredb" => "Список відновлення бази даних: ",
	"child_human_listDBuserrestore" => "Список відновлення користувачів баз даних: ",

	"common_showAllData" => "Показати все",
	"common_server_resource_limit" => "Обмеження ресурсів сервера",
	"common_access_is_denied" => "Доступ заборонено",

	"child_human_logtransStart" => "Будь ласка, зачекайте, користувач переноситься",

	"child_human_logtransStartFromRemote" => "Будь ласка, зачекайте, користувач переноситься з віддаленого сервера",

	"child_human__yandexGetBackup" => "Отримання резервної копії з ЯндексДиска",
	"common_control_packet_menager" => "Керування через пакетний менеджер",
	"common_install_version" => "Встановлено версію",
	"commonGmailWarning" => "Доступний менше xxxМб, Створення резервної копії неможливе. Будь ласка, звільніть місце.",
	"commonFewSpace" => "Не вистачає пам`яті. Необхідно додатково ",
	"commonFewSpaceMsg" => "Необхідно додатково ",
	"commonSizeMb" => "мб",
	"commonEnoughSpace" => "Достатньо місця. Завантаження.",
	"human_backupNoAvailUserForBackup" => "Користувачі, зазначені в задачі резервного копіювання, Недоступні для резервного копіювання",

	"human_dropbox_message_createbackup_failed" => "Помилка підключення при створенні резервного копіювання на Dropbox. Підключення до Dropbox неможливе, перевірте актуальність токенів.",
	"human_gdrive_message_createbackup_failed" => "Помилка підключення при створенні резервного копіювання на Gdrive. Підключення до Gdrive неможливе, перевірте актуальність токенів.",
	"human_yandex_message_createbackup_failed" => "Помилка підключення при створенні резервного копіювання на Yandex. Підключення до Yandex неможливе, перевірте актуальність токенів.",
	"human_ftp_message_createbackup_failed" => "Помилка підключення при створенні резервного копіювання на FTP. Підключення до FTP неможливе, перевірте правильність логіна, пароля.",
	"human_FailedConnWhileCreateBackupRemote" => "Помилка підключення при створенні резервного копіювання на удаленный сервер. Пожалуйста, перевірте налаштування зєднання.",

	"humanUserListLockBackup" => "Для цих користувачів неможливо зробити резервну копію, оскільки ще один процес резервного копіювання вже працює: ",
	"humanUserListLockRestore" => "Для цих користувачів неможливо зробити резервну копію, оскільки ще один процес відновлення резервного копіювання вже запущений: ",

	"humanUserListLockBackupRestAct" => "Для цих користувачів неможливо відновити резервну копію, оскільки ще один процес резервного копіювання вже працює: ",
	"humanUserListLockRestoreRestAct" => "Для цих користувачів неможливо відновити резервну копію, оскільки ще один процес відновлення резервного копіювання вже запущений: ",
	"humanDownBackuoFromFTP" => "Резервне копіювання з FTP",
	"humanDownBackuoFromFTPFewSpace" => "Не вистачає місця на FTP",

	"childHumanBackupGdriveFailedConn" => "Помилка підключення до gDrive. Відновлення перервано. Немає змін.",
	"childHumanBackupGdriveFailedConnUpload" => "Помилка підключення до gDrive. Бекап на gDrive не завантажено.",
	"childHumanBackupGdriveConnOk" => "Підключення до gDrive успішно.",

	"childHumanRestoreEmail" => "Список відновлення облікових записів пошти: ",
	"childHumanRestoreAll" => "всі",
	"commonAllItems" => "Всі",
	"childHumanmakeDataBackupInfo" => "Запис інформації про резервну копію",
	"child_humanGetdropboxBackup" => "Отримання резервної копії з Dropbox",
	"childHumanmakeUnlock" => "Розблокування користувача",
	"commonCustomRestFromfileUserNotExistStop" => "Відновлення перервано, оскільки резервне копіювання є вибірковим і не містить інформації користувачів. Вказаний користувач не існує в системі: ",
	"childHumanrestorefromfileStream" => "Відновлення резервної копії з обраного архіву",
	"childHumanrestoreLoggingRotate" => "Відновлення налаштувань ротацї логів",
	"childHumanrestoreHashmon" => "Відновлення налаштувань контроля хеш сум",
	"childHumanrestoreGroups" => "Відновлення групи користувача",
	"childHumanrestorePlans" => "Відновлення тарифа користувача",
	"childHumanrestoreCrons" => "Відновленняние крон завдань користувача",
	"child_letsRegen" => "Генерація сертификату letsencrypt для нового IP",
	"common_userNotInJailphp" => "Редагування php.ini недоступне - Користувач не розміщений в Jail PHP",
	"common_restphpiniuserjailok" => "Відновлення php.ini успішно",
	"childHumanrestorephpini" => "Відновлення налаштувань phpini",
	"child_human_checkauthRemoteServer" => "Перевірка авторизації до віддаленого сервера",
	"common_file" => "Файл",
	"common_erroroccu" => "Виникла помилка: ",
	"common_users" => "Користувачі",
	"common_applybtn" => "Застосовувати",
	"common_domains" => "Домени",
	"common_cancelbtn" => "Скасування",
	"common_selectAll" => "Обрати все",
	"common_processfinish" => "Процес завершений",
	"common_paramwitherror" => "Параметри містять помилку",
	"common_status" => "Статус",
	"common_configtitle" => "Конфігурація",
	"common_denyaccess" => "Немає доступу",
	"common_see" => "Подивитися",
	"common_param" => "Параметри",
	"common_diskpart" => "Дискові розділи",
	"common_countconnport" => "Кількість портових з`єднань",
	"common_dnscount" => "DNS зон",
	"common_fastsearche" => "Пошук знаходить сайти, пакети, email",
	"common_failedparam_pass" => "У паролі заборонено використовувати символи \\\ / &apos; &quot;",
	"license_empty" => "У вас немає ліцензії",
	"license_check_data" => "Перевірте дату:",
	"license_panel" => "Панель керування",
	"license_correct_date" => "Якщо це відрізняється, виправте дату використовуючи:",
	"license_support" => "Якщо дата правильна, зверніться в технічну підтримку на сайті",
	"access_denied_cluster" => "Сервер, підключений до кластера, керування цього модуля лише на master сервері."
);
