<?php

$lang = array(
    'crontab'           => 'Налаштування CRON',
    'clear_script'          => 'Чистий скрипт',
    'cron_ownvalue'          => '...',
    'cron_mon'          => 'Понеділок',
    'cron_tue'          => 'Вівторок',
    'cron_wed'          => 'Середа',
    'cron_thu'          => 'Четвер',
    'cron_fri'          => 'Пятниця',
    'cron_sat'          => 'Субота',
    'cron_sun'          => 'Неділя',
    'cron_*_short'          => '*',
    'cron_mon_short'          => 'Пн',
    'cron_tue_short'          => 'Вт',
    'cron_wed_short'          => 'Ср',
    'cron_thu_short'          => 'Чт',
    'cron_fri_short'          => 'Пт',
    'cron_sat_short'          => 'Сб',
    'cron_sun_short'          => 'Нд',
    'cron_min_fail_format'          => 'Неправильний формат період запуску хвилини',
    'cron_hours_fail_format'          => 'Неправильний формат період запуску години',
    'cron_days_fail_format'          => 'Неправильний формат період запуску дні',
    "cron_suspended_acc"=>"Додавання, редагування, Видалення Cron завдань заблоковано. Будь ласка, зверніться до адміністратора.",
	
    'cron_install'          => 'Встановлено',
    'cron_noinstall'          => 'Не встановлено',
    'cron_add_comand'          => 'Додати команду',
    'cron_delete'          => 'Вилучити',
	'cron_delete_process'  => 'Видаляється...',
    'cron_edit'          => 'Редагувати',	
    'cron_save'          => 'Зберегти',		
    'cron_cansel'          => 'Відмінити',	
    'cron_service'          => 'CROND сервіс',	
    'cron_status'          => 'Статус CROND сервісу',
    'cron_install_cr'          => 'Встановити CROND',
    'cron_delete_cr'          => 'Видалити CROND',
    'cron_reinstall_cr'          => 'Перевстановити CROND',
    'cron_detail'          => 'Детальніше',
    'cron_hide'          => 'Сховати',
    'cron_control'          => 'Керування CROND',
    'cron_start'          => 'Старт',
    'cron_stop'          => 'Стоп',
    'cron_reboot'          => 'Рестарт',
    'cron_task'          => 'Завдання CROND',
    'cron_select_user'          => 'Обрати користувача',
    'cron_nocheck'          => 'не обрано',
    'cron_add'          => 'Зберегти email',
    'cron_changes'          => 'Зміни успішно збережено.',
    'cron_null'          => 'Неправильний формат email',
    'cron_minute'          => 'Хвилина',
    'cron_hour'          => 'Година',
    'cron_day'          => 'День',
    'cron_month'          => 'Місяць',
    'cron_week'          => 'тижні',
    'cron_comand'          => 'Команда',
    'cron_user_email'          => 'Email (Для надсилання сповіщень):',
    'cron_save_ok'          => 'Дані успішно змінено',

    'cron_command_err'          => 'Помилка в полі команда',
    'cron_day_err'          => 'Некоректно зазначений день тижня',
    'cron_month_err'          => 'Некоректно зазначений місяць',
    'cron_username_err'          => 'Неправильне імя користувача',
    'cron_params_err'          => 'Помилка в параметрах',
    'cron_start_ok'          => 'Запущений',
    'cron_stop_ok'          => 'Зупинений',
    'cron_start_failed'          => 'запуск завершився з помилкою',
    'cron_inprogress_oper'          => 'Будь ласка зачекайте',
    'cron_inprogress_oper_finish'          => 'Операція завершена',
    'cron_notins_ok'          => 'Не встановлений',
    'cron_ins_ok'          => 'Встановлено',
	'cron_no_tasks'          => 'Немає завдань',
    'cron_job_add_ok'          => 'Завдання успішно додано',
    'cron_demo_mess'          => 'У демо-режимі всі зміни мають лише візуальний характер., Фактично, крон завдання не редагується, не створюються і не видаляються.',

    'cron_testrunjob'          => 'Виконати',
    'cron_hintAddJob'          => 'Приклад команди для додавання:<br/>1. /usr/bin/phpXX/bin/php /home/user/script.php, де ХХ - версія php<br/><br/>2. Приховування виходу повідомлень сценарію<br/> /usr/bin/phpXX/bin/php -q /home/user/script.php >/dev/null 2>/dev/null<br/><br/> 3. /usr/bin/wget -t 1 -O - `http://site.com/script.php?p1=a&p2=b`',
    'cron_hintAddJobPHPAllow' => 'Доступні версії php: ',
    'cron_comand_sucessf' => 'Команда виконана.<br>',

    'cronChangeJobStatusOk' => 'Статус завдання успішно змінено',
    'cronChangeJobStatusHint' => 'Активація/деактивація завдання',

	
);


