<?php

$lang = array(
    'ftp' => 'FTP',
    'start' => 'Запустити',
    'stop' => 'Зупинити',
    'default_vsftpd' => 'Відновити стандартний vsftpd.conf',
    'default_pureftpd' => 'Відновити стандартний pure-ftpd.conf',
    'default_proftpd' => 'Відновити стандартний proftpd.conf',
    'homedir_user' => 'Домашній каталог користувача',
    'delete_homedir_user'=>'Видалити кореневий каталог користувача',
    'ftp_path'=>'Домашній каталог',
    "ftp_quota_use"=>"Використання",
    "ftp_quota_avail"=>"Доступно",
    "ftp_change_pass"=>"Змінити пароль",
    "ftp_change_pass_placeholder"=>"Введіть новий пароль",
    "ftp_change_quota"=>"Змінити квоту",
    "ftp_change_quota_placeholder"=>"Введіть розмір квоти",
    "ftp_change_currennt_quota"=>"Поточна квота",
    "ftp_action"=>"Дії",
    "ftp_error_add_user_exist"=>"Користувачем з таким ім`ям існує",
    "ftp_success_add_user"=>"Користувач доданий",
    "ftp_deleted"=>"Видалений",
    "ftp_installed"=>"Встановлено",
    "ftp_reinstalled"=>"Перевстановлено",
    "ftp_install"=>"Встановити",
    "ftp_reinstall"=>"Перевстановити",
    "ftp_delete"=>"Видалити",
    "ftp_start"=>"Запустити",
    "ftp_stop"=>"Зупинити",
    "ftp_restart"=>"Перезапустити",
    "ftp_stat"=>"Статус",
    "ftp_server"=>"ФТП сервер",
    "ftp_stat_started"=>"Запущено",
    "ftp_stat_started_failed"=>"Запуск помилки",
    "ftp_stat_stopped"=>"Зупинено",
    "ftp_stat_restarted"=>"Перезапущено успішно",
    "ftp_process_launched"=>"Операція запущена, будь ласка, зачекайте...",
    "ftp_process_finished"=>"Операцію завершено.",
    "ftp_configure_share"=>"Налаштувати",
    
    "ftp_conf_edit"=>"Редагувати налаштування",
    "ftp_conf_save"=>"Зберегти",
    "ftp_conf_save_file"=>"Зберегти у файл",
    "ftp_conf_save_success"=>"Збережено успішно",
    "ftp_restore_default_settings"=>"Відновити стандартні налаштування",
    "ftp_restore_default_settings_success"=>"Стандартні установки відновлені",
    "ftp_repairmyconf"=>"Відновити мої установки",
    "ftp_repairmyconf_success"=>"Мої установки відновлені",

    "ftp_login"=>"Логін",
    "ftp_usage"=>"Використання",
    "ftp_quota"=>"Квота",
    "ftp_search_user"=>"Знайти",
    "ftp_accounts"=>"ФТП акаунти",
    "ftp_search_user_holder"=>"Введіть логін",
    "ftp_pagesize"=>"Кількість облікових записів на сторінці",

    "ftp_useradd"=>"Додати користувача ФТП",
    "ftp_pass_new"=>"Пароль",
    "ftp_homedir"=>"Домашня папка",
    "ftp_newuser_add"=>"Додати ФТП обліковий запис",
    "ftp_newuser_add_success"=>"Користувач доданий",
    "ftp_edit_user_sub"=>"Редагувати користувача",
    "ftp_delete_user_sub"=>"Видалити",
    "ftp_edit_user_quota"=>"Змінити квоту",
    "ftp_edit_user_pass"=>"Змінити пароль",
    "ftp_edit_user_quota_title"=>"ФТП квота",
    "ftp_edit_user_quota_mb"=>"Мб",
    "ftp_edit_user_quota_cancel"=>"Скасувати",
    "ftp_edit_user_quota_file"=>"Змінити квоту на файли",

    "ftp_edit_pass_enter"=>"Пароль",
    "ftp_edit_pass_enter_again"=>"Повторіть пароль",
    "ftp_edit_pass_strength_pass"=>"Надійність пароля",
    "ftp_edit_cancel"=>"Скасувати",
    "ftp_del_user"=>"Видалити користувача",
    "ftp_del_homedir"=>"Видалити домашню папку користувача",
    "ftp_del_user_cancel"=>"Скасувати",
    "ftp_del_user_confirm"=>"Видалити",
    "ftp_del_user_process"=>"Видаляється...",
    "ftp_config_ftp_client"=>"Налаштувати ФТП клієнт",
    
    "ftp_count_accept"=>"Застосувати",
    "ftp_user_exist"=>"Користувач вже існує",
    "ftp_import_ok"=>"Імпорт виконано успішно",
    "ftp_import_failed"=>"Імпорт виконано з помилкою",

    "ftp_selectftpacc"=>"Виберіть користувача",

    "ftp_searchftpacc"=>"Введіть ім`я користувача",

    "ftp_addaftpsubacc"=>"Додати ФТП субаккаунт",

    "ftp_noftpins"=>"ФТП сервер не встановлений. Зверніться до адміністратора",

    "ftp_user_login_new_wrong"=>"Неправильний формат логіна користувача",
    "ftp_user_login_new_wrong_null"=>"Введіть логін",
    "ftp_user_login_pass_null"=>"Введіть пароль",
    "ftp_user_userdir_null"=>"Введіть домашню папку",
    "ftp_user_userdir_wrong"=>"Неправильний формат домашньої папки",

    "ftp_user_quota_null"=>"Введіть розмір квоти",
    "ftp_user_quota_wrong"=>"Невірний формат квоти. Має бути ціле число",

    "ftp_user_add_ok"=>"Користувач успішно доданий",

    "ftp_generatelog_userfolder"=>"Згенерувати логи",
    "ftp_generatelog_ok"=>"Логи згенеровані успішно",
    "ftp_cron_run_failed"=>"Увага! CROND не запущений на сервері. Модуль може працювати некоректно. Встановіть та запустіть crond для коректної роботи.",

    "ftp_suspended_acc"=>"Додавання, редагування, видалення ФТП облікових записів заблоковано. Будь ласка, зверніться до адміністратора.",
    "ftp_setting"=>"Налаштування ФТП сервера",
    "ftp_not_instaled"=>"Не встановлено",
    "ftp_p_f"=>"pure-ftpd",
    "ftp_proftpd"=>"proftpd",
    "ftp_det"=>"Докладніше",
    "ftp_hide"=>"Приховати",
    "ftp_ns"=>"Не вибрано",
    "ftp_f_e"=>"Для експертів",
    "ftp_f_l"=>"Для користувачів",
    "ftp_y"=>"yes",
    "ftp_n"=>"no",
    "ftp_on"=>"on",
    "ftp_off"=>"off",
  
    "ftp_pass_change_ok"=>"Пароль успішно змінено",
    "ftp_quota_change_ok"=>"Квота успішно змінена",

    "ftp_adduser_failed_overlimit"=>"Перевищений ліміт ФТП облікових записів. Максимальна кількість ФТП облікових записів ",

    "ftp_nousersadded"=>"Користувачі не створені",
    "ftp_noaccounts"=>"Немає облікових записів",
    "ftp_not_passwd_for_passwd"=>"Паролі не співпадають",
    "ftp_main_ftpacc"=>"Головний ФТП обліковий запис. Видалення неможливе",
    "ftp_quota_not_use"=>"Квота не використовується",
    "ftp_quota_hint"=>"Для безлімітної квоти введіть 0",
    "ftp_user_readonly"=>"Тільки читання",
    "ftp_user_readonly_res_ok_save"=>"Доступ для фтп-акаунта змінено успішно",
    "ftp_pathMainFTP"=>"Домашня папка головного ФТП облікового запису",
    "ftp_remove_user_error"=>"Помилка видалення файлів. У цій директорії знаходяться сайти ",
    "ftpChangePassMain"=>"Увага! Зміна пароля головного фтп облікового запису також призведе до встановлення такого ж нового пароля на вхід до панелі.",
	
);
