<?php
$lang = array(
    "hashmon"=>"Контроль хеш сум",
    "hashmon_path"=>"Каталог моніторингу",
    "hashmon_addnewmon"=>"Редагування завдання моніторингу",
    "hashmon_addnewmonbtn"=>"Додати",
    "hashmon_period_run"=>"Період запуску",
    "hashmon_period_run_day"=>"Щодня",
    "hashmon_period_run_week"=>"Тижня",
    "hashmon_period_run_month"=>"Щомісячно",
    "hashmon_period_run_time"=>"Час запуску",
    "hashmon_period_run_time_hh"=>"гг",
    "hashmon_period_run_time_mm"=>"хх",
    "hashmon_period_run_time_weeksel"=>"Виберіть дні тижня для запуску",
    "hashmon_period_run_time_weeksel_mon"=>"Пн",
    "hashmon_period_run_time_weeksel_tue"=>"Вт",
    "hashmon_period_run_time_weeksel_wed"=>"Ср",
    "hashmon_period_run_time_weeksel_thu"=>"Чт",
    "hashmon_period_run_time_weeksel_fri"=>"Пт",
    "hashmon_period_run_time_weeksel_sat"=>"Сб",
    "hashmon_period_run_time_weeksel_sun"=>"Нд",
    "hashmon_period_run_time_datesel"=>"Вкажіть дати для запуску",
    "hashmon_period_run_time_datesel_del"=>"Видалити",
    "hashmon_period_run_time_datesel_add"=>"Додати дату запуску",
    "hashmon_period_run_time_sendemailafterscan"=>"Надіслати емейл після завершення",
    "hashmon_period_run_time_status"=>"Статус",
    "hashmon_run_includeonly"=>"Шукати тільки",
    "hashmon_run_includeonly_placeholder"=>"Вкажіть розширення файлів через , ; або пробіл. Наприклад: php,txt; sh py. Вказати каталог: dir:/home/folder. Допускається запис у кілька рядків",
    "hashmon_run_includeonly_placeholder_full"=>"Вкажіть розширення файлів через , , або пробіл.<br/>Наприклад: php,txt;sh py.<br/>Вказати каталог: dir:/home/folder.<br/>Вказати каталог з пошуком вибраних розширень: dir:/folder/||txt||php<br/>Допускається запис у кілька рядків",
    "hashmon_run_exclude"=>"Виключити файли",
    "hashmon_run_exclude_placeholder"=>"Вкажіть розширення файлів через , , або пробіл. Наприклад: php,txt; sh py.",
    
    "hashmon_createhash"=>"Створити знімок",
    "hashmon_hashlist_path"=>"Шлях",
    "hashmon_hashlist_date"=>"Час створення",
    "hashmon_hashlist_mainhash"=>"Основний",
    "hashmon_hashlist_option"=>"Опції",
    "hashmon_hashlist_delete"=>"Видалити",
    "hashmon_hashlist_select"=>"Вибрати для порівняння",
    
    "hashmon_wrongdir"=>"Вказана неправильна директорія",
    "hashmon_pleasewait"=>"Будь ласка, зачекайте",
    "hashmon_nofindbymask"=>"За заданим фільтром моніторингу файли не знайдені",
    "hashmon_findbymask"=>"Знімок створено",
    "hashmon_pathnotexist"=>"Вказаної директорії не існує",
    "hashmon_option_removehash"=>"Видалити знімок",
    "hashmon_option_setmain"=>"Призначити знімок основним",
    "hashmon_option_viewhash"=>"Переглянути знімок",
    "hashmon_option_denydeletehash"=>"Ви не є власником цього знімка",
    "hashmon_option_comparehash"=>"Порівняти",
    
    
    
    
    "hashmon_option_uncheck"=>"Прибрати виділення",
    "hashmon_option_complete_compare"=>"Порівняння виконано успішно",
    "hashmon_hashlist_no"=>"Знімки ще не створювалися",
    "hashmon_hashlist_table_title"=>"Список знімків",
    "hashmon_comphash_table_title"=>"Список виконуваних процесів порівняння знімків",
    "hashmon_comphash_table_title_noproc"=>"Немає запущених процесів",
    "hashmon_comphash_table_title_captch1"=>"Знімок 1",
    "hashmon_comphash_table_title_captch2"=>"Знімок 2",
    "hashmon_comphash_table_title_captch_createtime"=>"Час створення",
    "hashmon_comphash_table_title_comp_starttime"=>"Час запуску",
    "hashmon_comphash_table_title_comp_completeperc"=>"Виконано: ",
    
    "hashmon_comphash_table_title_finish"=>"Список завершених порівнянь знімків",
    "hashmon_stop_comp"=>"Зупинити",
    
    "hashmon_comphash_table_compared_no"=>"Немає виконаних порівнянь знімків",
    "hashmon_comphash_table_compared_view"=>"Переглянути результат",
    "hashmon_comphash_table_compared_manage"=>"Керування",
    "hashmon_comphash_table_compared_remove_rescomp"=>"Видалити",
    "hashmon_comphash_table_compared_view_rescomp"=>"Переглянути",
    "hashmon_comphash_table_compared_del_deny"=>"Немає прав для видалення результату",
    "hashmon_comphash_table_compared_view_deny"=>"Немає прав для перегляду результату",
    
    "hashmon_comphash_table_compared_view_title"=>"Перегляд результату порівняння знімків",
    "hashmon_comphash_table_compared_view_newin"=>"Нові файли: ",
    "hashmon_comphash_table_compared_view_remove"=>"Видалені файли: ",
    "hashmon_comphash_table_compared_view_newin_not"=>"не виявлено",
    "hashmon_comphash_table_compared_view_diff"=>"Різниця у файлах між знімками: ",
    "hashmon_comphash_table_compared_view_diff_no"=>"файли не знайдені",
    "hashmon_comphash_seldomain"=>"Виберіть домен",
    "hashmon_comphash_nodomainuser"=>"Немає доменів",
    
    "hashmon_add2cronjobs"=>"Додати завдання",
    "hashmon_updatecronjobs"=>"Оновити",
    "hashmon_removecronjobs"=>"Скасувати",
    "hashmon_namejob"=>"Ім`я завдання",
    "hashmon_namejob_exist"=>"Завдання з вказаним ім`ям вже існує. Придумайте інше.",
    "hashmon_namejob_exist_noedit"=>"Завдання із зазначеним ім`ям не існує.",
    "hashmon_namejob_empty"=>"Ім`я завдання не може бути порожнім.",
    "hashmon_wrongdir_format"=>"Неправильний формат директорії для сканування",
    "hashmon_wrong_namejob"=>"Неправильний формат імені завдання",
    "hashmon_wrong_findonlywith"=>"Невірний формат поля Шукати тільки з розширенням",
    "hashmon_wrong_findonlywithout"=>"Невірний формат поля Виключити файли з розширенням, папки",
    "hashmon_wrong_period"=>"Неправильний формат Період",
    "hashmon_wrong_timehourmin"=>"Неправильний формат Час запуску",
    "hashmon_wrong_weekdays"=>"Неправильний формат Дні тижня",
    "hashmon_wrong_numbermonth"=>"Невірний формат Дата запуску",
    "hashmon_job_save_complete"=>"Успішно збережено",
    "hashmon_job_list"=>"Список завдань моніторингу",
    
    "hashmon_job_listtable_title_name"=>"Ім`я",
    "hashmon_job_listtable_title_stat"=>"Статус",
    "hashmon_job_listtable_title_timerun"=>"Час запуску",
    "hashmon_job_listtable_title_opt"=>"Опції",
    
    "hashmon_job_listtable_title_nojobsadd"=>"Завдання моніторингу не додані",
    "hashmon_job_notifyemail"=>"Email для повідомлень",
    "hashmon_job_notifyemail_hint"=>"Після завершення роботи завдання моніторингу буде надіслано повідомлення на вказаний емейл зі статистикою змінених, віддалених та доданих файлів",
    "hashmon_job_notifyemail_format"=>"Введіть емейли через ;, або пробіл",
    "hashmon_job_selmaincapt"=>"Виберіть базовий знімок",
    "hashmon_job_selmaincapt_hint"=>"З вибраним знімком буде виконано порівняння на виявлення нових, віддалених та змінених файлів.<br/>Якщо ще немає знімка, будь ласка, спочатку створіть його перед додаванням завдання моніторингу",
    "hashmon_delcapt_comp_succ"=>"Порівняння знімків видалено.",
    "hashmon_emaillistnotify_wrong"=>"Невірний формат поле емейл",
    "hashmon_notexistmaincapt"=>"Вибраний головний знімок не існує",
    "hashmon_job_status"=>"Активно",
    
    'hashmon_period_intime' => ' в ',
    'hashmon_period_ondays' => 'за числами ',
    'hashmon_period_day' => 'Щодня',
    'hashmon_period_week' => 'Тижня',
    'hashmon_period_month' => 'Щомісячно',
    'hashmon_weekly_short_arr' => array('Пн','Вт','Ср','Чт','Пт','Сб','Нд'),
    
    
    'hashmon_job_runnow' => 'Виконати',
    'hashmon_job_edit' => 'Редагувати',
    'hashmon_job_remove' => 'Видалити',
    'hashmon_tablejob_title_maincapt' => 'Базовий знімок',
    'hashmon_tablejob_removedeny' => 'У вас немає прав на видалення цього завдання моніторингу',
    'hashmon_tablejob_removeok' => 'Завдання видалено',
    'hashmon_email_erorr_send' => 'Помилка надсилання листа зі статистикою моніторингу',
    'hashmon_email_res_monit' => 'Результат моніторингу директорії',
    'hashmon_hash_removerow_selected' => 'Видалити зазначені',
    'hashmon_denyusespecsymbol' => 'В імені завдання заборонено використовувати символи _ і пробіл',
    'hashmon_oraddjob' => 'або',
    'hashmon_oraddjob_btn' => 'Додати завдання',
    'hashmon_firstcreatehash' => 'Знімків немає. Спочатку створіть знімок',
    'hashmon_selallcheck' => 'Вибрати все',
    'hashmon_oraddjob_timet' => 'Додати завдання до розкладу',
    'hashmon_timettitle' => 'Розклад',
    'hashmon_sel2capt2comp' => 'Виберіть 2 знімки для порівняння',
    
    

);


