<?php
$lang = array(
    'hostacc' => 'Хост-акаунти',
    'hostacc_suspended_sites_ok' => 'Сайти на хост акаунті заблоковані.',
    'hostacc_unsuspended_sites_ok' => 'Сайти на хост акаунті розблоковані.',
    'hostacc_suspended_ftp_ok' => 'ФТП на хост акаунті заблоковано.',
    'hostacc_unsuspended_ftp_ok' => 'ФТП на хост акаунті розблоковано.',
    'hostacc_suspended_email_ok' => 'Пошта на хост акаунті заблокована.',
    'hostacc_unsuspended_email_ok' => 'Пошта на хост обліковому записі розблокована.',
    'hostacc_suspended_cron_ok' => 'Cron на хост акаунті заблоковано.',
    'hostacc_unsuspended_cron_ok' => 'Cron на хост акаунті розблоковано.',
    'hostacc_suspended_panel_ok' => 'Доступ до панелі користувача заблоковано.',
    'hostacc_unsuspended_panel_ok' => 'Доступ до панелі розблоковано.',
    'hostacc_suspended_shell_ok' => 'Шелл доступу користувачеві заблоковано.',
    'hostacc_unsuspended_shell_ok' => 'Шелл доступу розблоковано.',
    'hostacc_suspended_full_ok' => 'Доступ користувача повністю заблокований.',
    'hostacc_unsuspended_full_ok' => 'Доступ користувача повністю розблокований.',
    'hostacc_unsuspended_user_del' => 'У вас не вистачає прав, щоб видалити цього користувача.',
    'hostacc_unsuspended_user_del_ok' => 'Користувач був успішно видалений.',


    'hostacc_stat_susp_sites_title' => 'Блокування сайтів',
    'hostacc_stat_susp_ftp_title' => 'Блокування ФТП',
    'hostacc_stat_susp_email_title' => 'Блокування пошти',
    'hostacc_stat_susp_cron_title' => 'Блокування Cron',
    'hostacc_stat_susp_shell_title' => 'Блокування Шелл',
    'hostacc_stat_susp_panel_title' => 'Блокування панелі',
    'hostacc_stat_susp' => 'Так',
    'hostacc_stat_unsusp' => 'Ні',
    'hostacc_stat_susp_reason' => 'Причина блокування',
    'hostacc_stat_unsusp_ftpuser_failed' => 'ФТП користувачі розблоковані з помилкою',

    'hostacc_stat_confirm_susp' => 'Підтвердити блокування',
    'hostacc_btn_susp' => 'Заблокувати',
    'hostacc_btn_unsusp' => 'Розблокувати',

    'hostacc_btn_susp_full' => 'Заблокувати повністю',
    'hostacc_btn_unsusp_full' => 'Розблокувати повністю',
    'hostacc_date_susp' => 'Дата останнього блокування',
    'hostacc_date_unsusp' => 'Дата останнього розблокування',

    'hostacc_delete_ip_from_acc_failed' => 'Вказані ip: <br/>{ips}<br/> використовуються в: <br/>{domains}<br/> Для зміни IP в конфігурації вказаних доменів вище виберіть один із доступних IP:<br />',
    'hostacc_data_unset_plan' => 'Не вказано',
    'hostacc_data_unset_group' => 'Не вказано',

    'lang_rootaccess' => 'Доступ ROOT',
    'lang_ftp_access_restart' => 'Перезавантаження FTP',
    'lang_ftp_access_install' => 'Переустановка FTP',
    'lang_is_reseller' => 'Посередник',
    'lang_is_reseller_planview' => 'Переглядати план посереднику',
    'lang_is_reseller_groupview' => 'Переглядати групу посереднику',
    'lang_is_reseller_groupcreate' => 'Створювати групу посереднику',
    'lang_is_reseller_plancreate' => 'Створити план посереднику',

    'msg_unlimited0' => 'необмежено',
    'msg_unlimited' => '&#8734',
    'msg_no_permission_suspend_sites' => 'Немає дозволу зупинити сайти!',
    'msg_no_permission_unsuspend_sites' => 'Немає дозволу запустити сайти!',
    'msg_no_permission_suspend_ftp' => 'Немає дозволу зупинити FTP!',
    'msg_no_permission_unsuspend_ftp' => 'Немає дозволу запустити FTP!',
    'msg_no_permission_suspend_shell' => 'Немає дозволу зупинити роботу оболонки!',
    'msg_no_permission_unsuspend_shell' => 'Немає дозволу запустити оболонку!',
    'msg_no_permission_suspend_cron' => 'Немає дозволу зупинити роботу CRON!',
    'msg_no_permission_unsuspend_cron' => 'Немає дозволу запустити CRON!',
    'msg_no_permission_suspend_panel' => 'Немає дозволу зупинити роботу панелі!',
    'msg_no_permission_unsuspend_panel' => 'Немає дозволу запустити панель!',
    'msg_no_permission_suspend_full' => 'Немає дозволу зупинити роботу повністю!',
    'msg_no_permission_unsuspend_full' => 'Немає дозволу зробити повний перезапуск!',

    'msg_no_permission_edit' => 'У вас немає права редагувати це.',
    'msg_no_group_name' => 'Немає групи',
    'msg_no_group_add_ok' => 'Група успішно додана',
    'msg_no_group_edit_ok' => 'Група успішно відредагована',
    'msg_seccess_del' => 'Успішно видалено',
    'msg_add_host_acct' => 'Додати хост-акаунт',
    'msg_edit_host_acct' => 'Редагувати хост-акаунт',
    'msg_save_host_acct' => 'Зберегти хост-акаунт',
    'msg_add_plan' => 'Додати тариф',
    'msg_edit_plan' => 'Редагувати тариф',
    'msg_edit_user' => 'Редагувати користувача',
    'msg_username' => 'Ім`я користувача:',
    'msg_passwd' => 'Пароль:',
    'msg_ip' => 'Айпі адреса:',
    'msg_group' => 'Група:',
    'msg_plan' => 'Тариф:',
    'msg_language' => 'Мова:',
    'msg_count_mailbox' => 'Кількість поштових скриньок:',
    'msg_bandwidth' => 'Трафік:',
    'msg_count_sites' => 'Кількість сайтів:',
    'msg_count_db' => 'MySQL баз:',
    'msg_count_subdomains' => 'Кількість DNS зон:',
    'msg_count_dns_zones' => 'Кількість DNS зон:',
    'msg_count_mailperhour' => 'Кількість листів за годину:',
    'msg_count_disk' => 'Місце на диску:',
    'msg_count_ftp_acct' => 'ФТП акаунти:',
    'msg_shell_access' => 'Шелл доступ:',
    'msg_nginx_access' => 'Дозволити змінювати розміри кешів для nginx:',
    'msg_owner' => 'Власник:',

    'msg_seccess_added' => 'Успішно додано',
    'msg_seccess_edit' => 'Успішно редаговано',

    'msg_only_number' => 'Вказуйте число в полі ',
    'msg_both_num_leter' => 'Вказуйте число або латинські літери в полі ',

    'msg_only_number_bandwith' => 'Використовуючи цифри вкажіть пропускну здатність',
    'msg_only_number_sites' => 'Використовуючи цифри, вкажіть кількість сайтів',
    'msg_only_number_subdomains' => 'Використовуючи цифри, вкажіть кількість піддоменів',
    'msg_only_number_databases' => 'Використовуючи цифри, вкажіть кількість БД',
    'msg_only_number_mailbox' => 'Використовуючи цифри, вкажіть кількість поштових скриньок',
    'msg_only_number_mailperhour' => 'Використовуючи цифри, вкажіть кількість листів на годину',
    'msg_only_number_ftp_acct' => 'Використовуючи цифри, вкажіть кількість аккаунтів ftp',
    'msg_only_number_disk' => 'Використовуючи цифри, вкажіть диск',
    'msg_both_lang' => 'Вкажіть мову',
    'msg_both_shell' => 'Вкажіть оболонку для використання',
    'msg_both_plan' => 'Вкажіть назву тарифу',
    'msg_both_template' => 'Вкажіть шаблон',


    'msg_everything_good' => 'Все виконано без помилок.',
    'msg_ip_wrong' => 'IP адреса неправильна',
    'msg_exists_plan' => 'Такий тариф вже існує',
    'msg_done' => 'Виконано',

    'msg_done_pass' => 'Пароль повинен містити мінімум 7 символів',
    'msg_done_username' => 'Ім`я користувача має містити максимум 8 символів',

    'msg_both_username' => 'Використовуючи цифри та латинські літери, вкажіть ім`я користувача. Мінімум 3 символи.',
    'msg_both_group' => 'Використовуючи цифри та латинські літери вкажіть ім`я групи',

    'msg_no_user_sel' => 'Це не належить користувачеві',
    'msg_everything' => 'Все добре',


    'msg_edit_or_add_group' => 'Додати нову групу або редагувати поточні →',
    'msg_edit_or_add_plan' => 'Додати новий тариф або редагувати поточні →',

    'js_lang_select_ok' => 'Мова успішно змінена',

    'tpl_host_add_plan' => 'Додати тарифний план',
    'tpl_host_edit_plan' => 'Редагувати тарифний план',
    'tpl_host_save_plan' => 'Зберегти тарифний план',
    'tpl_host_add_new_plan' => 'Додати новий тариф',
    'tpl_host_plan_name' => 'Назва тарифу:',
    'tpl_host_bandwidth' => 'Трафік:',
    'tpl_host_disk' => 'Диск:',
    'tpl_host_sites' => 'Сайти:',
    'tpl_host_subdomains' => 'DNS зони:',
    'tpl_host_databases' => 'Бази даних:',
    'tpl_host_mailbox' => 'Поштові скриньки:',
    'tpl_host_mailperhour' => 'Листів на годину:',
    'tpl_host_ftp_acct' => 'ФТП акаунти:',
    'tpl_host_shell_access' => 'Shell доступ:',
    'tpl_host_lang' => 'Мова:',
    'tpl_host_lang_noselect' => 'Не вибрано',

    'tpl_host_groups_acct' => 'Групи хост-акаунтів',
    'tpl_host_current_group' => 'Поточна група:',
    'tpl_host_groupEditortitle' => 'Редактор груп',
    'tpl_host_create_new_group' => 'Створити нову',
    'tpl_host_name_new_group' => 'Ім`я нової групи:',
    'tpl_host_select_not_defined' => 'не визначено',
    'tpl_host_select_yes' => 'вкл',
    'tpl_host_select_no' => 'викл',
    'tpl_host_select_form_save' => 'Зберегти',
    'tpl_host_select_form_del' => 'Видалити',

    'tpl_host_list_title' => 'Всі хост-акаунти',
    'tpl_host_list_login' => 'Логін',
    'tpl_host_list_plan' => 'Тариф',
    'tpl_host_list_homefolder' => 'Домашня папка',
    'tpl_host_list_ip' => 'IP',
    'tpl_host_list_disk' => 'Диск',
    'tpl_host_list_group' => 'Група',
    'tpl_host_list_control' => 'Управління',
    'tpl_host_list_edit' => 'Редагувати',
    'tpl_host_list_delete' => 'Видалити',
    'tpl_host_list_t_plan' => 'Тарифний план',
    'tpl_host_list_t_plans' => 'Тарифні плани',

    'tpl_host_single_title' => 'Інформація про хост-аккаунт',
    'tpl_host_single_action' => 'Дії:',
    'tpl_host_single_abort' => 'Скасування',
    'tpl_host_single_create_date' => 'Дата створення:',
    'tpl_host_single_edit_date' => 'Дата останньої зміни:',
    'tpl_host_single_domain' => 'Домен',
    'tpl_host_single_ip' => 'IP',
    'tpl_host_single_home' => 'Домашній каталог',
    'tpl_host_single_aliases' => 'Аліаси',
    'tpl_host_single_triger_on' => 'Розблокувати',
    'tpl_host_single_triger_off' => 'Заблокувати',
    'tpl_host_single_change_lang' => 'Змінити мову',

    'lang_host_api' => 'Доступ по API',
    'lang_host_apifull' => 'Повний доступ до API(адміністратор)',
    'apifull_off' => 'Недостатньо прав для виконання API запиту',

    'hostacc_suspended_sites' => 'Додавання, редагування, видалення сайтів заблоковано. Будь ласка, зверніться до адміністратора.',
    'hostacc_del_process' => 'Видаляється...',
    'hostacc_successf_add' => 'Хост аккаунт успішно доданий',

    'hostacc_change_pass_label' => 'Пароль',
    'hostacc_change_pass_label1' => 'Введіть новий пароль',
    'hostacc_change_pass_label2' => 'Повторіть новий пароль',
    'hostacc_change_pass_pass_diff' => 'Введені паролі не співпадають.',
    'hostacc_change_pass_exec' => 'Змінити пароль',
    'hostacc_change_pass_exec_ok' => 'Пароль успішно змінено.',

    'hostacc_refresh_user_cache' => 'Оновити статистику користувача',
    'hostacc_refresh_user_cache_btn' => 'Оновити',
    'hostacc_refresh_user_cache_ok' => 'Статистика користувача успішно оновлена',

    'hostacc_user_search' => 'Пошук',
    'hostacc_return_main' => '← Повернутися до списку хост-акаунтів',
    'hostacc_user_search_res_empty' => 'Нічого не знайдено',

    'hostacc_user_search_pleasewait' => 'Виконується пошук...',

    'msg_only_number_dnz_zones' => 'Використовуючи цифри, вкажіть кількість DNS зон',
    'hostacc_sel_addgroup' => 'Додайте групу',
    'hostacc_sel_addpackage' => 'Додайте тариф',
    'hostacc_noaddhostacc_yet' => 'Хост-акаунти ще не додані',
    'hostacc_no_plans' => 'Тарифні плани ще не додані',

    'hostacc_updatecache_detail' => 'Виконати перерахунок статистики: кількість сайтів, поштові скриньки, використане місце, кількість ФТП-акаунтів, кількість баз даних.',

    'hostacc_user_alreadyexist' => 'Користувач з таким ім`ям вже існує',
    'hostacc_user_userhaventdomain' => 'Ще немає доданих доменів',
    'hostacc_user_signin' => 'Увійти',
    'hostacc_user_signin_warning' => 'При вході під вибраний користувач ви будете розавторизовані з-під поточного. <br/>Підтвердити авторизацію ',
    'hostacc_user_signin_warning_yes' => 'Так',
    'hostacc_user_signin_warning_no' => 'Ні',
    'hostacc_user_signin_failed' => 'Помилка авторизації. Потрібно скинути пароль для користувача.',
    'hostacc_user_signin_process' => 'Авторизація...',
    'hostacc_user_plan_not_set' => 'Не вказано',

    'hostacc_header_admin_param' => 'Все, що не визначено, заборонено.',
    'hostacc_header_user_param' => 'Все, що не визначено, дозволено.',
    'hostacc_chache_name' => 'Змінити ім`я',
    'hostacc_input_name' => 'Введіть нове ім`я',
    'hostacc_suc_change' => 'Успішно виконано',
    'hostacc_suc_change_empty' => 'Порожнє значення в назві групи',
    'hostacc_error_name_group' => 'Помилка в назві',
    'hostacc_error_no_user' => 'Такого користувача не існує',
    'hostacc_confirm_userdel' => 'Підтвердіть видалення користувача',
    'hostacc_confirm_userdel_yes' => 'Так',
    'hostacc_confirm_userdel_no' => 'Ні',

    'hostacc_confirm_universal_yes' => 'Так',
    'hostacc_confirm_universal_no' => 'Ні',

    'hostacc_usernotexist' => 'Вказаного користувача не існує',

    'hostacc_stat_susp_sites_hint' => 'Сайти заблоковані',
    'hostacc_stat_susp_ftp_hint' => 'ФТП заблоковано',
    'hostacc_stat_susp_email_hint' => 'Пошта заблокована',
    'hostacc_stat_susp_cron_hint' => 'Cron заблоковано',
    'hostacc_stat_susp_panel_hint' => 'Панель заблокована',
    'hostacc_stat_susp_full_hint' => 'Доступ повністю заблокований',
    'hostacc_stat_susp_reason_hint' => 'Причина блокування: ',
    'hostacc_stat_susp_reason_hint_notset' => 'не вказано',
    'hostacc_incorecly_simbol' => 'Заборонений символ у назві тарифу',

    'hostacc_createjailuser' => 'Jail оточення',
    'hostacc_createjailuserhint' => 'Користувач буде поміщений в jail оточення для обмеження доступу',

    'hostacc_jailTitle' => 'Налаштування Jail',
    'hostacc_jailStatusTitle' => 'Jail Shell',
    'hostacc_jailStatusTitlePHP' => 'Jail PHP',
    'hostacc_jailStatusSave' => 'Зберегти',
    'hostacc_jailStatusDesel' => 'Вимкнути всім Jail Shell',
    'hostacc_jailStatusSel' => 'Включити всім Jail Shell',
    'hostacc_jailStatusDeselPHP' => 'Вимкнути всім Jail PHP',
    'hostacc_jailStatusSelPHP' => 'Включити всім Jail PHP',
    'hostacc_jailStatusRebuild' => 'Застосувати',
    'hostacc_jailStatusSetResOk' => 'Jail оточення змінено успішно',
    'hostacc_jailStatusSetResFail' => 'Jail оточення не змінено',
    'hostacc_jailPHPHint' => 'PHP буде виконуватися в jail оточення. Доступно лише для мосту fastcgi(php-fpm)',
    'hostacc_jailnewaccShell' => 'Нові хост-акаунти розміщувати в Jail Shell',
    'hostacc_jailnewaccPhp' => 'Нові хост-акаунти розміщувати в Jail PHP',
    'hostacc_jailStatusAutoNewAcc' => 'Зберегти',
    'hostacc_jailStatusAutoNewAccSaveok' => 'Збережено успішно. <br/>Якщо було змінено Список пакетів доступних у Jail, необхідно виконати перебудову Jail за допомогою таблиці внизу',

    'hostacc_jailerrorMountMysql' => 'Помилка монтування сокету mysql',

    'hostacc_confirmDelPlan' => 'Підтвердіть видалення тарифу',
    'hostacc_limit_mysql_user' => 'Ліміт mysql з`єднань для user',
    'hostacc_max_questions' => 'MYSQL ліміт на кількість запитів за годину',
    'hostacc_max_updates' => 'MYSQL ліміт на редагування даних за годину',
    'hostacc_max_connections' => 'MYSQL ліміт на одночасні підключення',
    'hostacc_max_user_connections' => 'MYSQL ліміт на підключення користувача за годину',
    'hostacc_error_msg_questions' => 'Використовуючи цифри, вкажіть значення max_questions',
    'hostacc_error_msg_updates' => 'Використовуючи цифри, вкажіть значення max_updates',
    'hostacc_error_msg_user_connections' => 'Використовуючи цифри, вкажіть значення max_user_connections',
    'hostacc_error_msg_connections' => 'Використовуючи цифри, вкажіть значення max_connections',
    'hostacc_jailreinit' => 'Виконується переініціалізація jail оточення користувачів. Будь ласка зачекайте.',
    'hostacc_jailreinitParams' => 'Наведені параметри: ',
    'hostacc_jailreinitParamsHost' => 'Встановити статус джейл оточення: ',
    'hostacc_jailreinitParamsPHP' => 'Встановити статус джейл оточення php: ',
    'hostacc_jailreinitParamsPHPForce' => 'Виконати перебудову віртуальних хостів користувачів: ',
    'hostacc_jailreinitParamsHostOn' => 'Увімкнути',
    'hostacc_jailreinitParamsHostOff' => 'Вимкнути',
    'hostacc_jailreinitParamsHostRebuildYes' => 'Так',
    'hostacc_jailreinitParamsHostRebuildNo' => 'Ні',
    'hostacc_jailreinitBaseOnHostConf' => 'Виконується переініціалізація джейл оточення на основі поточних настройок користувача.',
    'hostacc_jailConfTitle' => 'Налаштування',
    'hostacc_jailListAppAvailInJail' => 'Список пакетів доступних у Jail',
    'hostacc_jailListAppAvailInJailHint' => 'Вказати через ; , пробіл або кожен пакет з нового рядка. Для застосування змін після збереження необхідно виконати перебудову jail для користувачів.',
    'hostaccPleaseWaitAuth' => 'Виконується авторизація. Будь ласка зачекайте.',

    'hostaccRebuldJailAll' => 'Перебудувати Jail оточення',
    'hostaccRebuldJailAllConfirm' => 'Підтвердіть перебудову Jail оточення для вибраних користувачів. <br/>Орієнтовний час виконання від 1 до 20 хвилин залежно від кількості вибраних користувачів.',
    'hostaccRebuldViewLog' => 'Дивитись лог',
    'hostaccRebuildAlreadyrun' => 'Перебудова Jail вже запущена. Подивіться, будь ласка, логи',
    'hostaccRebuildStartOk' => 'Перебудова Jail успішно запущена. Перегляд лога за кнопкою Дивитись балку. <br/>У процесі перебудови Jail заборонені будь-які операції з Jail. <br/>Будь ласка, дочекайтеся завершення операції.',
    'hostaccRebuildStartFailed' => 'Помилка вхідного списку користувачів',
    'hostaccRebuildViewLogBtn' => 'Дивитись лог перебудови Jail',
    'hostaccRebuildListUser' => 'Список користувачів для перебудови: ',
    'hostaccRebuildStartJailShell' => 'Перебудова Jail Shell',
    'hostaccRebuildStartJailPHP' => 'Перебудова Jail PHP',
    'hostaccRebuildFinish' => 'Jail перебудова завершена',
    'hostaccerror_e' => 'Помилка. Зарезервовано значення mysql (1E або 2e і тд.)',

    'hostacc_max_user_task' => 'Максимальна кількість завдань (порожньо - необмежена)',
    'hostacc_max_user_memory' => 'Максимальна кількість пам`яті в MB (порожньо - необмежена)',
    'hostacc_max_user_cpu' => 'Максимальне навантаження CPU у % (100% - 1 ядро,[200%...], порожньо - необмежено)',
    'hostacc_max_user_ior' => 'Максимальне IO читання (порожньо - необмежено)',
    'hostacc_max_user_iow' => 'Максимальне IO запису (порожньо - необмежено)',
    'hostacc_empty_log_jail' => 'Логи з перебудови jail, не знайдені.',
    'hostacc_user_reserv_system' => 'Користувач зарезервований системою.',
    'hostacc_error_name_numper_all' => 'Хостаккаунт не повинен складатися з одних цифр.',
    'hostacc_error_connect_mysql' => 'Користувач не може бути вилучений. Помилка підключення до бази даних',
    'hostacc_error_umount_user' => 'Помилка встановлення директорій користувача.',
    'hostacc_error_clear_rc_local' => 'Помилка очищення rc.local',
    'hostacc_error_add_user_linux' => 'Помилка додавання користувача linux',
    'hostacc_error_add_user_err' => 'Хостаккаунт додано.',
    'hostacc_error_error_mount' => 'Помилка монтування',
    'hostaccChangePassForFTP' => 'Змінити пароль для FTP',
    'hostacc_disable_brainy_connect' => 'Сервіс brainy-socket.service вимкнено.',
    'hostacc_error_brainy_connect_not_found' => 'Сервіс brainy-socket.service не знайдено.',

    'hostacc_RebuildJailSkeleton' => 'Перебудувати Jail Skeleton',
    'hostacc_RebuildJailSkeletonOK' => 'Jail Skeleton успішно перебудовано. Для застосування змін необхідно виконати перебудову jail для користувачів',
    'hostacc_RebuildJailSkeletonHint' => 'Створює/оновлює копію системних файлів для роботи Jail',
    'hostacc_error_set_limit_mysql' => 'При встановленому mariadb 10.4 вимкнено обмеження на кількість запитів за годину',
    'hostacc_error_set_limit_mysql_time' => 'При встановленому mariadb 10.4 вимкнено обмеження на редагування даних за годину',
    'hostacc_error_set_limit_mysql_connection' => 'При встановленому mariadb 10.4 вимкнено обмеження на одночасні підключення',
    'hostacc_error_set_limit_mysql_connection_time' => 'При встановленому mariadb 10.4 вимкнено обмеження на підключення користувача за годину',
    'tpl_host_nginx_access' => 'Дозволити змінювати розміри кешів для nginx:',
    'tpl_host_sharedata_title' => 'Загальні дані',
    'hostacc_listhostacc' => 'Список хост-акаунтів',
    'hostacc_server_resource_systemd'=>'Обмеження ресурсів користувачеві',
    'hostacc_grouprightAdmin'=>'Адміністраторські',
    'hostacc_grouprightUser'=>'Користувацькі',
    'hostacc_blockextended'=>'Розширене блокування',
    'hostacc_error_remove_user' => 'Помилка видалення користувача. Доступ для root в панелі закритий, і цей користувач знаходиться в групі root для керування панеллю.',
    'hostacc_error_remove_group_root' => 'Помилка видалення або редагування групи. Доступ для root на панелі закритий, і ця дія заблокує вхід до панелі користувача.',
    'hostacc_block_all_sites' => 'Заблокувати всі сайти',
    'hostacc_block_all_sites_list' => 'Список заблокованих сайтів',
    'hostacc_stat_susp_shell_hint' => 'Shell заблоковано',
    'hostacc_error_add_system_jail' => 'Помилка додавання системних пакетів або директорій',
    'hostacc_error_add_ip_tarif' => 'Значення ip, у полі тарифу порожнє. Перевірте правильність цього параметра',

);

