<?php

$lang = array(
    'index_logout'		=> 'Вийти',
    'index_home'		=> 'Головна',
    'index_search'		=> 'Пошук',
	'index_quick_search' => 'Швидкий пошук',
	'index_section_search' => 'Пошук по разділам',

    'index_control'		=> 'Керування',
    'index_conf_server'		=> 'Налаштування сервера',
    'index_host_acct'		=> 'Хост-акаунти',
    'index_groups_acct'		=> 'Группи хост-акаунтів',
    'index_plans_acct'		=> 'Тарифи хост-акаунтів',
    'index_manage_ip'		=> 'Менеджер IP адрес',
    'index_manage_mem'		=> 'Менеджер ресурсів',
    'index_update'		=> 'Оновлення',
    'index_reboot'		=> 'Перезавантаження сервера',

    'index_www'			=> 'Вебсервер',
    'index_www_install'		=> 'Встановлення вебсервера',
    'index_php_install'		=> 'Встановлення і налаштування PHP',
    'index_php_delete'		=> 'Видалення вебсервера і PHP',

    'index_pass_folder'		=> 'Пароль на діректорію',
    'index_jmp_http'		=> 'Переадресація HTTP',
    'index_jmp_sites'		=> 'Переадресація сайтів',
    'index_apacserver_optimization' => 'Оптимізація работи сайту',
	'index_apacserver_error_pages' => 'Сторінки помилок',
	'index_webserver_config' => 'Індивідуальні доналаштування віртхостів',

    'index_databases'		=> 'База данних',
    'index_mysql_db'		=> 'Керування MySQL/MariaDB',
    'index_phpmyadmin'		=> 'Управление PHPMyAdmin',

    'index_email'		=> 'Пошта',
    'index_email_down'		=> 'Сервіс вихідної пошти',
    'index_email_up'		=> 'Сервіс вхідної пошти',
    'index_more_install'		=> 'Масове встановлення сервісів',
    'index_init_mail'		=> 'Налаштування поштового сервісу',
    'index_control_queue'		=> 'Керування чергою',
    'index_control_spf'		=> 'Керування SPF',
    'index_control_dmarc'		=> 'Керування DMARC',
    'index_mail_acct'		=> 'Почтові акаунти',
    'index_jmp_mail'		=> 'Перенаправлення пошти',
    'index_control_opendkim'		=> 'Керування Opendkim',
    'index_control_clamv'		=> 'Керування Clamav',
    'index_control_spam'		=> 'Керування Spamassassin',
    'index_auto_answer'		=> 'Автовідповідач',
    'index_mail_filtet'		=> 'Фільтрація пошти',
    'index_mail_statistic'		=> 'Статистика листів',
    'index_mail_default'		=> 'Поштова скринька по замовчуванню',

    'index_dns'				=> 'Сервер імен',
    'index_dns_control_zone'		=> 'Керування DNS зонами',
    'index_dns_ns'		=> 'Неймсервери',
    'index_dns_init_claster'		=> 'Кластер DNS',

    'index_application'			=> 'Програми',
    'index_application_manager'		=> 'Менеджер програм',
    'index_autoinit_cms'		=> 'Автоустановщик CMS',
	'index_user_cms'		=> 'Встановити CMS користувачу',
    'index__file_manager'		=> 'Файловий менеджер',
    'index_ssh'				=> 'SSH сервер',
    'index_cron'			=> 'CRON',
    'index_ftp'				=> 'FTP сервер',

    'index_static'		=> 'Статистика',
    'index_manage_proc'		=> 'Менеджер процесів',
    'index_top'			=> 'TOP',
    'index_trafic_use'		=> 'Використання трафіку',
    'index_average_load'		=> 'Среднє навантаження',
    'index_static_processing'		=> 'Засоби обробки статистики',
    'index_logging'		=> 'Логування',
    'index_monitoring'		=> 'Моніторинг сервісів',
    'index_mysql_process'	=> 'MySQL Processlist',
    'index_status_web'		=> 'Статус вебсервера',
	'index_hardware_info' => 'Інформація про сервер',
    'index_smart_mon' => 'S.M.A.R.T мониторинг',

    'index_cert_ssl'			=> 'Сертифікати SSL',
    'index_cert_service'		=> 'Сертифікати сервісів',
    'index_cert_user'			=> 'Користувацькі сертифікати',

    'index_backup'			=> 'Резервне копіювання',
    'index_config_backup'		=> 'Налаштування бекапів',
    'index_jmp_server'			=> 'Трансфер між серверами',

    'index_network'			=> 'Мережа',
    'index_network_tools'		=> 'Керування IPTables',
    'index_stat_connect'		=> 'Моніторинг зєднань',
	'index_csf'				=> 'CSF Firewall',
	'index_speedtest' => 'Швидкість каналу сервера',

    'index_security'			=> 'Безпека',
    'index_antivirus'			=> 'Антивірус',
    'index_mod_security'	=> 'Керування ModSecurity',

    'index_general'			=> 'Основне',
    'index_general_info'		=> 'Загальна информация',

    'index_webwww'			=> 'WWW',
    'index_web_sites'			=> 'Сайти',
    'index_web_virthost'			=> 'Додаткові налаштування сайтів',
    'index_cloudflare'			=> 'Cloudflare',
    'index_black_domain'			=> 'Заборонені домени',
    'index_dns_editing'			=> 'DNS редактор',

    'index_ftp_section'			=> 'FTP',
    'index_ftp_section_acct'		=> 'FTP акаунти',

    'index_webserver_control'		=> 'Керування вебсервером',

    'index_section_mail'		=> 'Пошта',
    'index_section_mailbox'		=> 'Поштові скриньки',
    'index_section_jmp_mail'		=> 'Поштові перенаправлення',
    'index_section_spf'			=> 'SPF',
    'index_section_dkim'		=> 'DKIM',
    'index_section_dmarc'		=> 'DMARC',

    'index_section_cert'		=> 'Сертифікати',
    'index_control_ssl'			=> 'Керування SSL',

    'index_sect_bd'			=> 'БД',
    'index_sect_bd_mysql'		=> 'База даних MySQL',
    'index_sect_bd_myadmin'		=> 'PHPMyAdmin',

    'index_sect_tools'			=> 'Утиліти',
    'index_sect_tools_cron'		=> 'CRON завдання',
    'index_sect_tools_backup'		=> 'Резервне копіювання',
    'index_sect_tools_fmanager'		=> 'Файловий менеджер',
    'index_sect_tools_cms'		=> 'Автовстановлювач CMS',

    'index_sect_info'			=> 'Інформація',
    'index_sect_info_monitor'		=> 'Моніторинг сервісів',
    'index_sect_info_log'		=> 'Логи',
    'index_sect_info_ns'		=> 'Наймсервери по замовчуванню',
    'index_sect_info_php'		=> 'Налаштування PHP',
    'index_sect_info_usage'		=> 'Викоримтання трафіка',
    'index_sect_info_average'		=> 'Среднє навантаження',
    'index_sect_info_stat'		=> 'Засоби статистики',

    'index_brainy_tel'		=> '',
    'index_brainy_msg'		=> '',

    'index_topinfo_ip'			=> 'Всі IP користувача',
    'index_topinfo_unlim'		=> 'необмежено',
    'index_topinfo_unlimited'	=> '&#8734',
    'webhost_configurator'		=> 'Індивидуальні доналаштування віртхостів',
    'index_blacklist'		=> 'Перевірка сервера в чорних списках',
    'index_mail_mailing'		=> 'Поштова розсилка',

    'index_databases_postgresql'		=> 'База даних PostgreSQL',

    'index_LogStatDom'		=> 'Керування логуванням сайтів',

    'index_cluster'		=> 'Кластер',
    'index_cluster_server'		=> 'Кластер серверів',
    'index_cluster_ip'		=> 'Кластер IP',
    'indexRouteMail'		=> 'Маршрутизація пошти',
    'index_cluster_mysql'		=> 'Кластер Бази данних',

    'index_controlpanel'		=> 'Панель керування сервером',
    'index_close'		=> 'Закрити',
	'index_stopautorefresh' => 'Зупинити автооновлення',
    'index_continueautorefresh' => 'Продовжити автооновлення',
    'index_method_withname' => 'Метод с іменем ',
    'index_notexistforjquery' => ' не існує для jQuery.tooltip',
    'index_date_fullJan' => 'Січеню',
    'index_date_fullFeb' => 'Лютий',
    'index_date_fullMar' => 'Березень',
    'index_date_fullApr' => 'Квітень',
    'index_date_fullMay' => 'Травень',
    'index_date_fullJun' => 'Червень',
    'index_date_fullJul' => 'Липень',
    'index_date_fullAug' => 'Серпень',
    'index_date_fullSep' => 'Вересень',
    'index_date_fullOct' => 'Жовтень',
    'index_date_fullNov' => 'Листопад',
    'index_date_fullDec' => 'Грудень',
    'index_date_fullJan_short' => 'Січ',
    'index_date_fullFeb_short' => 'Лют',
    'index_date_fullMar_short' => 'Бер',
    'index_date_fullApr_short' => 'Кві',
    'index_date_fullMay_short' => 'Тра',
    'index_date_fullJun_short' => 'Чер',
    'index_date_fullJul_short' => 'Лип',
    'index_date_fullAug_short' => 'Сер',
    'index_date_fullSep_short' => 'Вер',
    'index_date_fullOct_short' => 'Жов',
    'index_date_fullNov_short' => 'Лис',
    'index_date_fullDec_short' => 'Гру',
    'index_date_mon' => 'понеділок',
    'index_date_tue' => 'вівторок',
    'index_date_wed' => 'среда',
    'index_date_thu' => 'четвер',
    'index_date_fri' => 'пятниця',
    'index_date_sat' => 'субота',
    'index_date_sun' => 'неділя',
    'index_date_mon_short' => 'пн',
    'index_date_tue_short' => 'вт',
    'index_date_wed_short' => 'ср',
    'index_date_thu_short' => 'чт',
    'index_date_fri_short' => 'пт',
    'index_date_sat_short' => 'сб',
    'index_date_sun_short' => 'нд',
    'index_date_mon_min' => 'Пн',
    'index_date_tue_min' => 'Вт',
    'index_date_wed_min' => 'Ср',
    'index_date_thu_min' => 'Чт',
    'index_date_fri_min' => 'Пт',
    'index_date_sat_min' => 'Сб',
    'index_date_sun_min' => 'Нд',
    'index_date_ready' => 'Готово',
    'index_date_prev' => 'Попер',
    'index_date_next' => 'Наст',
    'index_date_today' => 'Сьогодні',
    'index_sect_graphs' => 'Графіки Моніторингу',

);
