<?php
$lang = array(
    'logging'		=> 'Логирование',
    'logging_log'		=> 'Логирование',
    'logging_select_user'		=> 'Выбрать пользователя:',
    'logging_not_selected'		=> 'Не выбран',	
    'logging_setting_rotation'		=> 'Настроить ротацию логов сервисов →',
    'logging_users_log'		=> 'Пользовательские архивированные логи',			
    'logging_download'		=> 'Скачать',		
    'logging_download_log'		=> 'Скачать данный кусок лога',	
    'logging_download_all_log'		=> 'Скачать весь текущий лог',		
    'logging_path_log'		=> 'Путь к файлу лога:',		
    'logging_searche_log'		=> 'Поиск по фразе в логе:',	
    'logging_show'		=> 'Отобразить',		
    'logging_prev_record'		=> 'Предыдущие записи',		
    'logging_next_record'		=> 'Следующие записи',		
    'logging_line_latest'		=> 'Строки (начиная с последней) от',		
    'logging_line_display'		=> 'Сколько строк отображать:',
    'logging_add_log_rotation'		=> 'Добавление логов в ротацию',	
    'logging_back_log'		=> '← Вернуться к логированию',	
    'logging_not_install'		=> 'Не установлен',		
    'logging_install'		=> 'Установить',			
    'logging_successfully'		=> 'Успешно установлено. Обновите страничку',
    'logging_stat_ins'		=> 'Активный',
    'logging_nologs'		=> 'Нет доступных логов',
    'logging_titlemanrot' => 'Управление ротацией',
    'logging_namelog' => 'Название лога',
    'logging_titlelog1' => 'Логи',

    'logging_rotUserLogsTitle' => 'Ротация логов пользователей',
    'logging_rotUserLogsHint' => 'Глобальное включение/отключение ротации логов всех пользователей',

    'logging_ConfPeriod' => 'Период запуска',
    'logging_ConfPeriodHourly' => 'Каждый час',
    'logging_ConfPeriodDaily' => 'Каждый день',
    'logging_ConfPeriodWeekly' => 'Каждую неделю',
    'logging_ConfPeriodMonthly' => 'Каждый месяц',
    'logging_ConfSave' => 'Сохранить',
    'logging_ConfSaveAllUser' => 'Применить для всех пользователей',
    'logging_ConfCountCountLogs' => 'Хранить количество старых логов',
    'logging_ConfCountCountLogsPlace' => 'Введите число',
    'logging_ConfCompress' => 'Сжатие',
    'logging_ConfFormat' => 'Формат имени',
    'logging_ConfFormatDate' => 'Дата',
    'logging_ConfFormatNumber' => 'Порядковый номер',
    'logging_ConfUserTitleConfigure' => 'Настройка ротации логов пользователя',

    'logging_activeServiceLog' => 'Делать ротацию логов',
    'logging_confLogrotSaveok' => 'Сохранено успешно',
    'logging_confLogrotEnDisOk' => 'Сохранено успешно',
    'logging_not_rotation' => 'Введите количество логов.',


);