<?php

$lang = array (
    'mailclient' => 'Поштові скриньки',
    'on'=> 'Увімкнути',
    'off'=> 'Вимкнути',
    'status_on'=>'Увімкнено',
    'status_off'=>'Вимкнено',
    
    'tpl_mail_autoanswer' =>'Автовідповідач',
    'tpl_mail_user' =>'Користувач',
    'tpl_mail_box' =>'Ящик',
    'tpl_mail_interval' =>'Інтервал',
    'tpl_mail_from' =>'Від',
    'tpl_mail_subject' =>'Тема',
    'tpl_mail_body_mail' =>'Тіло листа',
    'tpl_mail_action' =>'Дія',
    'tpl_mail_is_active' =>'Активний',
    'tpl_mail_add' =>'Додати',
    'tpl_mail_del' =>'Видалити',
    'tpl_mail_edit' =>'Редагувати',
    'tpl_mail_save' =>'Зберегти',
    'tpl_mail_abort' =>'Скасувати',
    
    'tpl_mail_antivir_control' => 'Управління антивірусом',
    'tpl_mail_antivir_status' => 'Стан:',
    'tpl_mail_on' => 'Увімкнути',
    'tpl_mail_off' => 'Вимкнути',
    'tpl_mail_tools' => 'Налаштування',
    
    'tpl_mail_account' => 'Поштові облікові записи',
    'tpl_mail_account_add' => 'Додавання облікового запису',
    'tpl_mail_account_box' => 'Акаунт',
    'tpl_mail_passwd' => 'Пароль',
    'tpl_mail_quota' => 'Квота',
    'tpl_mail_email' => 'Email',
    'tpl_mail_email_mail' => 'Пошта',
    'tpl_mail_enter_passwd' => 'Введіть пароль',
    'tpl_mail_open_roundcube' => 'Roundcube',
    'tpl_mail_open_squire' => 'Squiremail',
    'tpl_mail_open_webmail' => 'Webmaillite',
    
    'tpl_mail_webmail' => 'Webmail',
    
    'tpl_mail_email_default' => 'Поштова скринька за замовчуванням',
    'tpl_mail_domen' => 'Домен',
    'tpl_mail_not_install' => 'Не встановлено',
    'tpl_mail_jmp_to' => 'Переслати на ',
    'tpl_mail_jmp_email' => 'Переслати на Email',
    'tpl_mail_jmp_email_all' => 'Перенаправлення пошти',
    'tpl_mail_jmp_domain_all' => 'Перенаправлення доменів',
    'tpl_mail_enter_email' => 'Введіть Email',
    'tpl_mail_failed_delivery' => 'Не вдалося доставити',
    'tpl_mail_blackhole' => 'Blackhole',
    
    'tpl_mail_service_noinst' => 'Сервіс не встановлено',
    'tpl_mail_service_norun' => 'Сервіс не запущений',
    'tpl_mail_service_control' => 'Управління сервісом',
    
    'tpl_mail_record_add' => 'Додавання запису',
    'tpl_mail_jmp_domain2from' => 'Домен, з якого перенаправляти',
    'tpl_mail_jmp_email2to' => 'Поштовий, на який надсилати',
    'tpl_mail_jmp_box_all' => 'Перенаправлення скриньок',
    'tpl_mail_jmp_box_source' => 'Email, з якого перенаправляти',
    'tpl_mail_jmp_box_target' => 'Email або конвеєр до програми (Pipe to a Program), на який відправляти (можна кілька, через кому)',
    'tpl_mail_jmp_box_target_save' => 'Зберегти листи у вихідній скриньці (можна бути створена в розділі поштові облікові записи)?',
    'tpl_mail_jmp' => 'Перенаправлення',

    'tpl_mail_control_opendkim' => 'Управління opendkim',
    'tpl_mail_control_opendmarc' => 'Управління opendmarc',
    'tpl_mail_control_clamav' => 'Управління clamav',
    'tpl_mail_control_spam' => 'Управління Spamassassin',
    'tpl_mail_enter_to_email' => 'Увійти до поштової скриньки',
    'tpl_mail_fine_tuning' => 'Тонке налаштування',
    'tpl_mail_options' => 'Опції',
    'tpl_mail_status' => 'Статус',
    'tpl_mail_filter' => 'Фільтрування пошти',
    'tpl_mail_filter_control' => 'Керування фільтрами',
    'tpl_mail_filters' => 'Фільтри',
    'tpl_mail_control' => 'Управління',
    'tpl_mail_mass_install' => 'Масова установка',
    'tpl_mail_control_queue' => 'Управління чергою',
    'tpl_mail_control_spf' => 'Управління SPF',
    'tpl_mail_control_dmarc' => 'Управління DMARC',
    'tpl_mail_filter_name' => 'Назва фільтра',
    'tpl_mail_rules' => 'Правила',
    'tpl_mail_filter_header' => 'Фільтр',
    
    'tpl_mail_rules_from' => 'Від',
    'tpl_mail_rules_subject' => 'Тема',
    'tpl_mail_rules_to' => 'Одержувач',
    'tpl_mail_rules_reply' => 'Відповідач',
    'tpl_mail_rules_bodytest' => 'Тіло листа',
    'tpl_mail_rules_any_header' => 'Будь-який заголовок',
    'tpl_mail_rules_any_recipient' => 'Будь-який отримувач',
    'tpl_mail_rules_no_deviver' => 'Не було надіслано',
    'tpl_mail_rules_error' => 'Зміст помилок',
    'tpl_mail_rules_id' => 'ID у черзі',
    'tpl_mail_rules_status' => 'Спам статус',
    'tpl_mail_rules_bar' => 'Спам рівень',
    'tpl_mail_rules_scope' => 'Спам об`єм',
    
    'tpl_mail_rules_contains' => 'Утримує',
    'tpl_mail_rules_match' => 'Збіг',
    'tpl_mail_rules_no_contains' => 'Не містить',
    'tpl_mail_rules_equals' => 'Рівне',
    'tpl_mail_rules_begin' => 'Починається з',
    'tpl_mail_rules_end' => 'Закінчується на',
    'tpl_mail_rules_no_begin' => 'Не починається з',
    'tpl_mail_rules_no_end' => 'Не закінчується на',
    'tpl_mail_rules_no_match' => 'Не збігається',
    'tpl_mail_rules_above' => 'Більше(числа)',
    'tpl_mail_rules_no_above' => 'Не більше(числа)',
    'tpl_mail_rules_below' => 'Менше (числа)',
    'tpl_mail_rules_no_below' => 'Не менше (числа)',
    
    'tpl_mail_rules_discrab' => 'Відхилити',
    'tpl_mail_rules_redirect' => 'Перенаправити',
    'tpl_mail_rules_fail' => 'Відмова',
    'tpl_mail_rules_stop' => 'Зупинити фільтр',
    'tpl_mail_rules_deliver' => 'Покласти до папки',
    'tpl_mail_rules_pipe' => 'Переправити програмі',
    
    'tpl_mail_mass_install_prog' => 'Масова установка ПЗ',
    'tpl_mail_setup' => 'Встановити',
    'tpl_mail_more' => 'Докладніше',
    'tpl_mail_hide' => 'Приховати',

	'tpl_mail_message_time' => 'Час',
    'tpl_mail_message_id' => 'ID повідомлення',
    'tpl_mail_message_sources' => 'Відправники',
    'tpl_mail_message_target' => 'Одержувачі',
    'tpl_mail_message_size' => 'Розмір',
    'tpl_mail_message_status' => 'Статус',
    'tpl_mail_message_action' => 'Дія',
    'tpl_mail_message_queue' => 'У чергу',
    
    'tpl_mail_receive_name' => 'Налаштування сервера вхідної пошти',
    'tpl_mail_receive_installed' => 'Встановлено',
    'tpl_mail_receive_working' => 'Працює',
    'tpl_mail_receive_more' => 'Докладніше',
    'tpl_mail_receive_hide' => 'Приховати',
    'tpl_mail_receive_install' => 'Встановити',
    'tpl_mail_receive_delete' => 'Видалити',
    'tpl_mail_receive_reinstall' => 'Перевстановлення',
    'tpl_mail_receive_start' => 'Запустити',
    'tpl_mail_receive_stop' => 'Зупинити',
    'tpl_mail_receive_restart' => 'Перезапустити',
    
    'tpl_mail_email_clients' => 'Поштові клієнти',
    
    'tpl_mail_send_name' => 'Налаштування сервера вихідної пошти',
    'tpl_mail_send_warning' => 'При установці сервер вихідної пошти Exim буде видалено',
    'tpl_mail_send_postfix' => 'Postfix',
    'tpl_mail_send_exim' => 'Exim',
    'tpl_mail_send_warning_postfix' => 'При установці сервер вихідної пошти Postfix буде видалено',
    'tpl_mail_send_dkim' => 'OpenDKIM',
    'tpl_mail_send_dmarc' => 'OpenDMARC',
    'tpl_mail_send_antispam' => 'Антиспам',
    'tpl_mail_send_antivirus' => 'Антивірус',
    
    'tpl_mail_spf_control' => 'Управління SPF',
    'tpl_mail_dmarc_control' => 'Управління DMARC',
    
    'tpl_mail_spf_select_user' => 'Виберіть користувача',
    'tpl_mail_spf_no_domain' => 'Немає доступних доменів або не знайдено зони для доменів',
    'tpl_mail_spf_domain' => 'Домен',
    'tpl_mail_spf_action' => 'Дія',
    'tpl_mail_spf_saved' => 'Запис',
    'tpl_mail_dmarc_select_user' => 'Виберіть користувача',
    'tpl_mail_dmarc_no_domain' => 'Немає доступних доменів',
    'tpl_mail_dmarc_domain' => 'Домен',
    'tpl_mail_dmarc_action' => 'Активація',
    'tpl_mail_dmarc_jmp' => 'Дія',
    'tpl_mail_dmarc_mailto' => 'Адреса для звітів',
    'tpl_mail_dmarc_saved' => 'Запис',
    
    'tpl_mail_rouncube' => 'Roundcube',
    'tpl_mail_webmaillite' => 'WebMailLite',

    'msg_mail_err_mysql_connect' => 'Помилка з`єднання з MySQL сервером: ',
    'msg_mail_webmail' => 'Webmail',
    'msg_mail_delete' => 'Видалити',
    'msg_mail_process_last_log' => 'Останній рядок команди виконання: ',
    'msg_mail_not_your_domain' => 'Це не ваш домен',
    'msg_mail_enter_def_action' => 'Вкажіть дію за промовчанням',
    'msg_mail_enter_email' => 'Введіть поштову скриньку',
    'msg_mail_process_ok' => 'Операція виконана успішно',
    'msg_mail_choose_user' => 'Виберіть користувача',
    'msg_mail_enter_domain' => 'Введіть домен',
    'msg_mail_already_domain' => 'Такий домен вже існує',
    'msg_mail_chouse_option' => 'Вкажіть опцію',
    'msg_mail_already_autoanswer' => 'Автовідповідач вже існує',
    'msg_mail_enter_time' => 'Вкажіть час',
    'msg_mail_enter_text' => 'Введіть текст',
    'msg_mail_enter_subject' => 'Тема',
    'msg_mail_enter_body' => 'Тіло листа',
    'msg_mail_ver_txt' => 'версія:',
    
    'msg_mail_run' => 'Запущено',
    'msg_mail_stoped' => 'Зупинено',
    'msg_mail_success_edit' => 'Редагування пройшло успішно',
    
    'js_mail_process_progress' => 'Іде процес встановлення... Зачекайте.',
    'js_mail_process_finish' => 'Процес завершено',
    'js_mail_not_install' => 'Не встановлений',
    
    'js_mail_wrong_pass' => 'Некоректний пароль!',
    'js_mail_client_prog' => 'Потрібно встановити поштові клієнти',
    'js_mail_progress' => 'Виконується...',
    'js_mail_process_on' => 'Увімкнено',
    'js_mail_process_off' => 'Вимкнено',
    'js_mail_email_error' => 'Введіть правильну поштову скриньку',
    'js_mail_passwd_error_len' => 'Пароль не може бути порожнім',
    'js_mail_err_source_domain' => 'Введіть правильний початковий домен',
    'js_mail_err_target_domain' => 'Введіть правильний домен призначення',
    'js_mail_err_source_email' => 'Введіть правильну початкову поштову скриньку',
    'js_mail_err_target_email' => 'Введіть правильну поштову скриньку призначення',
    'js_mail_err_already' => 'Домен/поштова скринька вже є у списку',
    'js_mail_jmp_to' => 'Переслати на ',
    'mailclient_del_process' => 'Видаляється...',
    
    'mailclient_emailexist' => 'Поштова скринька вже існує',
    'mailclient_invalid_comand' => 'Неправильна команда',
    'mailclient_status' => 'Статус',
    'mailclient_command_succsecfully' => 'Команда виконана',
    
    "mailclient_addmail_failed_overlimit"=>"Перевищено ліміт поштових акаунтів. Максимальна кількість поштових акаунтів ",
    "mailclient_addmail_failed_quotaformat"=>"Неправильний формат квоти.",
    "mailclient_spf_addemail"=>"SPF",
    "mailclient_dkim_addemail"=>"DKIM",
    "mailclient_dmarc_addemail"=>"DMARC",
    "mailclient_new_quota"=>"Нова квота, мб",
    "mailclient_new_pass"=>"Новий пароль",
    "mailclient_change_quota"=>"Змінити квоту",
    "mailclient_change_pass"=>"Змінити пароль",
    "mailclient_change_pass_quota"=>"Змінити пароль, квоту",
    "mailclient_change_auto_text"=>"Змінити текст",
    "mailclient_change"=>"Зберегти",
    "mailclient_successfully_done"=>"Успішно виконано",
    "mailclient_no_rights"=>"У Вас недостатньо прав для виконання цієї операції",
    "mailclient_empty_field"=>"Поле має бути заповнене",
    
    "mailclient_usernothaveemailbox"=>"Користувач не має поштових скриньок або немає відповідності фільтру",
    "mailclient_usernothaveredirect"=>"Користувач не додав перенаправлень",
    "mailclient_user_nothavesites"=>"Користувач не має доданих сайтів",

    "mailclient_autoresponder"=>"Увімкнути автовідповідач",
    "mailclient_text_autoresponder"=>"Наберіть текст для автовідповідача",
    "mailclient_error_number"=>"Неправильний формат значення",
    "mailclient_not_text"=>"Текст повідомлення має бути заповнений",
    "mailclient_autoresponder_check"=>"Автовідповідач",
    "mailclient_autoresponder_text"=>"Текст повідомлення",
    "mailclient_data_not_corected"=>"Неправильні дані",
    "mailclient_change_text"=>"Змінити текст",
    "mailclient_change_text_check"=>"Потвердити",
    "mailclient_change_succecfully"=>"Дані успішно змінені",
    "mailclient_saving"=>"Йде збереження",
    "mailclient_loging"=>"Поштові логи",
    "mailclient_load_statistic"=>"Завантажити статистику",
    "mailclient_not_email"=>"У користувача немає поштових скриньок",
    "mailclient_not_email_statistic"=>"На жаль, сьогодні ще статистики немає.",
    "mailclient_statistic"=>"Статистика отримання та оправлення листів",
    "mailclient_filter"=>"Фільтри електронної пошти",
    "mailclient_email_filter"=>"Виберіть поштову скриньку",
    "mailclient_filter_name"=>"Назва фільтра",
    "mailclient_filter_condition"=>"Умова фільтра",
    "mailclient_filter_act"=>"Дія фільтра",
    "mailclient_filter_create"=>"Створити фільтр",
    "mailclient_filter_ot"=>"Від.",
    "mailclient_filter_tema"=>"Тема",
    "mailclient_filter_do"=>"До.",
    "mailclient_filter_reply"=>"Відповісти",
    "mailclient_filter_text"=>"Текст",
    "mailclient_filter_any_title"=>"Будь-який заголовок",
    "mailclient_filter_not_previously_delivered"=>"Раніше не доставлялося",
    "mailclient_filter_error_message"=>"Є повідомлення про помилку",
    "mailclient_filter_ind_list"=>"Індетифікатор списку",
    "mailclient_filter_state_spam"=>"Стан небажаної пошти",
    "mailclient_filter_junk_mail"=>"Панель для небажаної пошти",
    "mailclient_filter_spam_evaluation"=>"Оцінка небажаної пошти",
    "mailclient_filter_contains"=>"Утримує",
    "mailclient_filter_regex"=>"Відповідає regex",
    "mailclient_filter_not_contains"=>"Не містить",
    "mailclient_filter_equal"=>"Рівнюється",
    "mailclient_filter_starts"=>"Починається з",
    "mailclient_filter_end"=>"Завершується на",
    "mailclient_filter_not_starts"=>"Не починається",
    "mailclient_filter_not_end"=>"Не закінчується на",
    "mailclient_filter_not_equal"=>"Не відповідає",
    
    "mailclient_filter_dell_message"=>"Видалити повідомлення",
    "mailclient_filter_redirect"=>"Перенаправити",
    "mailclient_filter_error_mes"=>"Помилка з повідомленням",
    "mailclient_filter_leave_processing_rules"=>"Залишити правила обробки",
    "mailclient_filter_deliver_folder"=>"Доставити до папки",
    "mailclient_not_user"=>"Користувач не відповідає",
    "mailclient_name_filter"=>"Неправильна назва фільтра мінімум 5 символів (a-z0-9_)",
    "mailclient_not_filter_1"=>"Не відповідність фільтру 1",
    "mailclient_not_filter_2"=>"Не відповідність фільтру 2",
    "mailclient_not_action"=>"Не існуюча дія",
    "mailclient_not_text_filter"=>"Текстовий фільтр не відповідає",
    "mailclient_not_email_reg"=>"Email не відповідає регулярному виразу",
    "mailclient_folder"=>"test/spam - папка та ім`я файлу в директорії email",
    "mailclient_error_folder"=>"Директорія не відповідає регулярному виразу",
    "mailclient_email_redirect"=>"Email для редагування",
    "mailclient_not_filter_include"=>"Встановлених фільтрів немає",
    "mailclient_n_filter"=>"Назва фільтра",
    "mailclient_filter_header_all" => "Всі фільтри",
    "mailclient_filter_header_add" => "Додати фільтр",
    
    
	"mailclient_action"=>"Дія",
    "mailclient_description_text"=>"*Увага! При складанні фільтра на текст враховуйте те, що повністю перевіряються всі заголовки і тіло листа.",
    "mailclient_description_filter"=>"Опис",
    "mailclient_description_tema"=>"*Увага! Деякі поштові сервери кодують тему листа залежно від довжини символів. Враховуйте це при складанні фільтрів.",
    "mailclient_description_text2"=>"**Деякі поштові сервери кодують тіло листа Content-Transfer-Encoding: base64. У таких випадках фільтр користувача безглуздий.",
    "mailclient_description2"=>"*Фільтр з однаковою назвою буде перезатерти створеним фільтром.",
    "mailclient_description3"=>"**Черговість фільтрів має значення. Фільтри виконуються зверху вниз (Після фільтра «Видалити повідомлення» подальші фільтри з тією самою умовою працювати не будуть).",
    "mailclient_mailing"=>"Поштове розсилання",
    
    
    "mailclient_not_group"=>"Немає списків передплатників",
    "mailclient_add_group"=>"Додати список передплатників",
    "mailclient_group_mailing_name"=>"Назва списку",
    "mailclient_group_mailing_description"=>"Опис списку",
    "mailclient_num_piople"=>"Кількість людей",
    "mailclient_view_list"=>"Керування списком",
    "mailclient_view"=>"Подивитися",
    "mailclient_remove_group"=>"Видалити список",
    "mailclient_add_in_list"=>"Додати до списку",
    "mailclient_error_group"=>"Назва списку не відповідає регулярному виразу",
    "mailclient_group_file_suceesuele"=>"Список передплатників успішно створено.",
    "mailclient_error_group_file"=>"Назва списку вже існує",
    "mailclient_name_user"=>"Ім`я передплатника",
    "mailclient_name_user2"=>"Прізвище передплатника",
    "mailclient_phone"=>"Телефон",
    "mailclient_address"=>"Адреса",
    "mailclient_not_data"=>"Не відноситься до даних",
    "mailclient_name_user_error"=>"Ім`я або прізвище передплатника не відповідає регулярному виразу",
    "mailclient_phone_error"=>"Номер телефону не відповідає регулярному виразу",
    "mailclient_address_error"=>"Адреса не відповідає регулярному виразу",
    "mailclient_not_all_data"=>"Немає всіх значень",
    "mailclient_group_mailing_none"=>"Список передплатників порожній",
    "mailclient_field"=>"Колонка",
    "mailclient_not_email_parser"=>"На жаль, парсер не знайшов email передплатників",
    "mailclient_not_file_prepere"=>"Відсутній файл обробки масиву",
    "mailclient_num_equal"=>"Кількість збігів - ",
    "mailclient_num_black_list"=>"Підписувачів у чорних списках - ",
    "mailclient_num_error"=>"Кількість помилок - ",
    "mailclient_add_users"=>"Додано передплатників - ",
    "mailclient_error_file_data"=>"Заборонений тип даних - ",
    "mailclient_error_file_save"=>"Не вдалося зберегти файл",
    "mailclient_parse_email"=>"Такий email існує",
    "mailclient_succes_remove"=>"Список передплатників успішно видалено.",
    "mailclient_subscription"=>"Підписано",
    "mailclient_subscription_send"=>"Стан",
    "mailclient_subscription_data"=>"Дата передплати",
    "mailclient_not_number"=>"не число",
    "mailclient_not_file"=>"немає файлу для редагування",
    //"mailclient_group_time_start"=>"Час запуску 00:00",
    //"mailclient_group_time_start2"=>"Час запуску",
    //"mailclient_error_description"=>"Опис не відповідає регулярному виразу",
    //"mailclient_error_time_start"=>"Час запуску не відповідає регулярному виразу",
    //"mailclient_start"=>"Запуск",
    //"mailclient_start_mail"=>"Запуск розсилки",

    "mailclient_save_changes"=>"Зберегти зміни",
    "mailclient_add_user"=>"Додати передплатника",
    "mailclient_email_user"=>"Email передплатника",
    
    "mailclient_add_user_header"=>"Додати передплатників",
    "mailclient_add_user_process_header"=>"Додавання передплатників",
    "mailclient_error_active"=>"Дія не відповідає регулярному виразу",
    //"mailclient_error_active"=>"Email має бути заповненим",
    "mailclient_succesfulle_add_user"=>"Підписувач успішно доданий.",
    "mailclient_error_add_user"=>"Помилка збереження передплатника. Можливо відсутній список.",
    
    
    "mailclient_remove_succesfully"=>"Підписник успішно видалено.",
    "mailclient_remove_send"=>"Підписникf відписано від розсилки",
    "mailclient_add_send"=>"Підписувач підписано на розсилку",
    "mailclient_add_black_list"=>"Чорний список",
    "mailclient_add_black_list_succ"=>" додано до чорного списку",
    "mailclient_add_black_list_succ_user"=>"Підписчик знаходиться в чорних списках",
    "mailclient_list_send"=>"Списки розсилок",
    "mailclient_mail"=>"Листи",
    
    "mailclient_text_1"=>"Значення, які при надсиланні листа замінюються",
    "mailclient_text_name"=>'{$name} - ім`я передплатника',
    "mailclient_text_email"=>'{$email} - email передплатника',
    "mailclient_text_last_name"=>'{$lastname} - прізвище передплатника',
    "mailclient_text_phone"=>'{$phone} - телефон передплатника',
    "mailclient_text_address"=>'{$address} - адреса передплатника',
    "mailclient_user_variable"=>' - змінна користувача',
    "mailclient_text_unsubscribe"=>'Відписатися',
    "mailclient_message_mailing"=>'Листи розсилки',
    "mailclient_message_not"=>'У вас немає листів',
    "mailclient_message_thema"=>'Тема листа',
    "mailclient_message_body"=>'Тіло листа',
    "mailclient_message_from"=>'Від кого',
    "mailclient_error_thema"=>'Тема листа не відповідає регулярному виразу',
    "mailclient_message_list"=>'Список листів',
    "mailclient_add_message"=>'Додати лист',
    "mailclient_error_id"=>'id повідомлення не відповідає регулярному виразу.',
    "mailclient_piople"=>'людина',
    "mailclient_add_new_message"=>'Додавання нового повідомлення',
    "mailclient_edit_message"=>'Редагування повідомлення',
    "mailclient_create_mailling"=>'Створити розсилку',
    "mailclient_select_mail"=>'Виберіть листа для розсилки',
    "mailclient_select_group_mailing"=>'Виберіть список розсилки',
    "mailclient_email_output"=>'Виберіть список розсилки',
    "mailclient_test_mail"=>'Тестовий лист',
    "mailclient_email_recipient"=>'Email одержувача',
    "mailclient_create_mailling_cron"=>'Створити розсилку',
    "mailclient_send_now"=>'Надіслати зараз',
    "mailclient_send_succec"=>'Лист успішно надіслано',
    "mailclient_add_mailing_send"=>'Розсилка листів додано до завдання',
    "mailclient_send_error"=>'Помилка надсилання листа',
    "mailclient_send_mailing"=>'Надіслані розсилки',
    "mailclient_send_data"=>'Дата надсилання',
    "mailclient_letter_list"=>'Лист, список',
    "mailclient_mailing_id"=>'ID розсилки',
    "mailclient_send_status"=>'Статус',
    "mailclient_num_piople_mailing"=>'Людина в розсилці',
    "mailclient_send_email"=>'Всього надіслано листів',
    "mailclient_open_email"=>'Відкрито',
    "mailclient_delivered_email"=>'Доставлено',
    "mailclient_not_send_email"=>'Заблоковано',
    "mailclient_date"=>'Дата',
    "mailclient_send_later"=>'Надіслати пізніше',
    "mailclient_send"=>'Надіслати',
    "mailclient_succec_remove"=>'Успішно видалено',
    "mailclient_send_ok"=>'Надіслано',
    "mailclient_send_not"=>'Блокований',
    "mailclient_send_expectation"=>'Чекання надсилання',
    "mailclient_not_message"=>'Немає повідомлень для розсилки',
    "mailclient_not_list_group"=>'Немає списків передплатників',
    "mailclient_data_time"=>'Дата та час на сервері',
    "mailclient_not_ecvaldata_time"=>'Вказаний час менше, ніж час на сервері.',
    "mailclient_autocorrect"=>'Автозаміна змінних спрацює лише якщо email існує у вибраному списку одержувачів.',
    "mailclient_attentconfonseroff"=>'Увага! Сервіс не запущений, але його секція включена до конфігурації - це може призвести до некоректної роботи пошти. Запустіть сервіс або заберіть його з конфігурації кнопкою нижче',
    "mailclient_used_total_message"=>"Використання МБ / Всього МБ / Повідомлень",
    "mailclient_overquota"=>"Перевищена квота",
    "mailclient_dbconnfailedbrainysql"=>"Помилка підключення до сервера баз даних MySql",
    "mailclient_no_domains"=>"Немає доданих доменів",
    "mailclient_please_wait"=>"Будь ласка, зачекайте.",
    "mailclient_view_list_header"=>"Перегляд списку",
    "mailclient_list_header"=>'Списки передплатників',
    
    "mailclient_add_single_user"=>'Додати одного передплатника',
    "mailclient_file_import"=>'Імпортувати з файлу',
    "mailclient_copy_insert"=>'Копіювати/вставити',
    
    "mailclient_add_user_text_line1"=>'Кожен передплатник з нового рядка.',
    "mailclient_add_user_text_line2"=>'В якості розділювачів даних одного передплатника використовується будь-який символ із |,;:',
    "mailclient_add_user_text_line3"=>'Допускаються файли .txt, .csv.',
    "mailclient_add_user_text_line4"=>'Для нормальної роботи з кирилицею зберігайте файл у кодуванні utf8.',
    "mailclient_add_user_text_placeholder"=>'ivanivanov@gmail.com;Іван;Іванов;Інші дані',
    
    "mailclient_mailing_header" => 'Розсилки',
    "mailclient_mailing_details_header" => 'Деталі розсилки',
    "mailclient_links_header" => 'Переходи за посиланням',
    "mailclient_create_mailing_header" => 'Створити розсилку',
    "mailclient_mailing_date_header" => 'Виберіть дату та час',
    "mailclient_create_message" => 'Створити лист',
    "mailclient_create_list_mailing" => 'Створити список розсилки',
    "mailclient_open" => 'Відкрито',
    
    'mailclient_all_links' => 'Всі посилання',
    'mailclient_links' => 'Посилання',
    'mailclient_coversions' => 'Переходи',
    
    'mailclient_each_recipient_header' => 'Докладніше по кожному одержувачу',
    
    'mailclient_authmailok' => 'Успішний вхід',
    'mailclient_customdomain' => 'Довільний домен',
    'mailclient_customdomain_hint' => 'Введіть домен',
    'mailclient_customdomain_failedformat' => 'Неправильний формат довільного домену.',
    
    'mailclient_clamav_autostart' => 'Автозавантаження',
    'mailclient_confirm_remove_email' => 'Підтвердіть видалення поштового облікового запису',
    'mailclient_add_email' => 'Додайте поштову скриньку',
    
    'mailclient_qualify_domain_title' => 'Налаштування вихідної пошти',
    'mailclient_qualify_domain_hint' => 'Для надсилання листів з підписом DKIM, SPF, використовуючи функцію mail без заголовків, потрібно задати домен у qualify_domain, який має DKIM, SPF запис',
    'mailclient_qualify_label' => 'Значення qualify_domain',
    'mailclient_qualifyCantSetQualifyNotJail' => 'Неможливо змінити qualify_domain. Користувач не в оточенні jail. Будь ласка, зверніться до адміністратора.' ,
    'mailclient_not_quality_domain' => 'У файлі конфігурації відсутня qualify_domain',
    'mailclient_qualify_save_failed' => 'Неправильний формат домену.',
    'mailclient_qualify_save_ok' => 'Збережено успішно.',
    'mailclient_error_add_root' => 'Користувачеві заборонено додати цю поштову скриньку',
    'mailclient_not_dirctory_email' => 'Немає директорії поштової скриньки',
    
    'mailclientmailTableNoDom' => 'Користувач не має доданих доменів',
    'mailclientmailTableTitle' => 'Маршрутизація пошти',
    'mailclientmailTableTh1' => 'Домен',
    'mailclientmailTableTh2' => 'Маршрутизація',
    'mailclientmailRouteUpdateOk' => 'Успішно оновлено',
    'mailclientmailRouteSelDom' => 'Виберіть домен',
    'mailclientmailRouteSelDomCur' => 'Поточний домен',
    'mailclientmailRouteLocal' => 'Локальний поштовий обмінник',
    'mailclientmailRouteRemote' => 'Видалений поштовий обмінник',
    'mailclientmailOtherMx' => 'Використання сторонніх записів MX',
    'mailclientmailOtherMxTypeHint'=>'<b>Локальний поштовий обмінник.</b> Система прийматиме пошту для цього домену. Система буде доставляти пошту до локальної поштової скриньки. <br/><b>Віддалений поштовий обмінник.</b> Система не прийматиме пошту для цього домену. Система завжди надсилатиме всі листи цього домену на поштовий сервер з меншим числом MX.',
    'mailclient_uppercase' => 'Локальну частину поштового облікового запису, використовуйте в нижньому регістрі.',
    'mailclient_empty_mail_account' => 'Не додано поштову скриньку, в поштових облікових записах',
    'mailclient_name_from' => 'Ім`я відправника',
    'mailclient_error_name_from' => 'Помилка імені відправника',
    'mailclient_empty_mail_service' => 'Не встановлені поштові програми (Roundcube,SquirrelMail)',
    'mailclient_searchmail'=>'Пошук поштової скриньки',


);
