<?php

$lang = array(
    'msg_js_mysql_status'	=> 'Не працює',
    'msg_mysql_error_num_db'	=> 'Помилка. Ви досягли максимальної кількості баз.',
    'msg_mysql_ok_priv'		=> 'Привілеї застосовані.',
    'msg_mysql_err_check_db'		=> 'Помилка перевірки DB.',
    'msg_mysql_err_check_user'		=> 'Помилка перевірки користувача.',
    'msg_mysql_ok_user_del'		=> 'Користувача успішно вилучено.',
    'msg_mysql_err_user_del'		=> 'Некоректне ім`я користувача.',
    'msg_mysql_ok_db_del'		=> 'База успішно вилучена.',
    'msg_mysql_err_db_del'		=> 'Помилка видалення бази.',

    'tpl_remove_delete'		=> 'Видалити',
    'tpl_remove_configure'	=> 'Налаштувати',
    'tpl_main_menu_mysql'	=> 'MySql',
    'tpl_main_menu_process'	=> 'MySql processlist',
    'tpl_mysql_nomysql'		=> 'Не встановлено',
    'tpl_mysql_nomyadmin'	=> 'Не встановлено',
    'tpl_mysql_more'		=> 'Докладніше',
    'tpl_mysql_hidden'		=> 'Приховати',
    'tpl_mysql_status_info'	=> 'MySql статус: ',
    'tpl_mysql_cnf_save'	=> 'Зберегти',
    'tpl_mysql_install_phpadmin'	=> 'Встановити phpMyAdmin',
    'tpl_mysql_phpadmin_status'	=> 'Phpmyadmin статус',
    'tpl_mysql_myadmin_install'	=> 'Встановити',
    'tpl_mysql_nodb'		=> 'Не додано жодної бази даних',
    'tpl_mysql_add_user'	=> 'Додати користувача',
    'tpl_mysql_add_db'		=> 'Додати базу даних',
    'tpl_mysql_jmp_promptly'		=> 'Перейти до phpMyAdmin відразу',
    'tpl_mysql_jmp_pass'		=> 'Перейти до phpMyAdmin з паролем',
    'tpl_mysql_jmp_only'		=> 'Перейти до phpMyAdmin',
    'tpl_mysql_select_all'		=> 'Позначити все',
    'tpl_mysql_external_access'		=> 'Відкрити зовнішній доступ',
    'tpl_mysql_external_access_all'	=> 'Відкрити зовнішній доступ будь-кому IP',
    'tpl_mysql_no_user'			=> 'Не додано жодного користувача',

    'tpl_mysql_no_user_select' => 'Немає користувачів',
    'tpl_mysql_no_base_select' => 'Немає баз даних',

    'tpl_mysql_hide'			=> 'Приховати',
    'tpl_mysql_name'			=> 'MySQL',
    'tpl_mysql_version'			=> 'Версія MySql:',
    'tpl_mysql_reinstall'		=> 'Перевстановити',
    'tpl_mysql_for_expert'		=> 'Для експертів',
    'tpl_mysql_for_user'		=> 'Для користувачів',
    'tpl_mysql_passwd_rename'		=> 'Триває процес зміни пароля. Зачекайте будь-ласка.',
    'tpl_mysql_update'			=> 'Оновлення',
    'tpl_mysql_update_force'		=> 'Форсоване оновлення',

    'js_mysql_delete'		=> 'Виконуємо видалення... ',
    'js_mysql_install'		=> 'Виконуємо встановлення... ',
    'js_mysql_passwd_file'	=> 'Будь ласка, заповніть поля пароля',
    'js_mysql_install_pass'	=> 'Встановлення завершено',
    'js_mysql_remove_pass'	=> 'Видалення завершено',
    'js_mysql_no_install'	=> 'Не встановлено',
    'js_mysql_no_error'		=> 'Без помилок',
    'js_mysql_error'		=> 'Помилка:',
    'js_mysql_process_done'	=> 'Процес запущений зачекайте...',
    'js_mysql_check_msg'	=> 'Йде процес зміни пароля. Не чіпайте mysql сервер',
    'js_mysql_server_notwork'	=> 'MySQL сервер не працює. Будь ласка зверніться до адміністратора',
    'js_mysql_db_noconnect'	=> 'Помилка приєднання до бази. Будь ласка зверніться до адміністратора',
    'js_mysql_db_nodata'	=> 'Помилка передачі даних. Спробуйте пізніше.',
    'js_mysql_db_nodata_nopass'	=> 'Новий пароль не може бути порожнім. Будь ласка, введіть новий пароль.',
    'js_mysql_passwd_root'	=> 'Пароль mysql root було змінено',
    'js_mysql_change_config'	=> 'Конфігурація mysql-сервера змінена',
    'js_mysql_restore_config'	=> 'Відновлено конфігурацію за замовчуванням',
    'mysql_show_all_users'	=> 'Виведення всіх користувачів',
    'mysql_show_error_users'	=> 'Масив користувачів порожній.',
    'mysql_show_error_root'	=> 'У вас недостатньо прав. Заберіть user_edit',
    'mysql_show_all_db'	=> 'Виведення баз користувача',
    'mysql_show_error_db'	=> 'Масив баз порожній.',
    'mysql_name_user_db_error'	=> 'Ім`я користувача порожнє.',
    'mysql_pwd_user_db_error'	=> 'Пароль для користувача бази порожній.',
    'mysql_not_name_db'	=> 'Назва бази даних має бути заповнена.',	
    'mysql_add_user_ok'	=> 'Користувач доданий.',
    'mysql_not_work_mysql'	=> 'Не працює mysql',
    'mysql_not_root_password'	=> 'Неправильний пароль Root mysql. Будь ласка, зв`яжіться з адміністратором',
    'mysql_user_exist'	=> 'Користувач існує',		
    'mysql_add_db_ok'	=> 'База даних створена',
    'mysql_add_db_exists'	=> 'База даних існує',	
    'mysql_list_privilegies'	=> 'Список привілеїв. ',	
    'mysql_not_privilegies'	=> 'Користувач не має привілеїв. Список привілеїв порожній.',
    'mysql_not_write_privilegies'	=> 'Неправильно написаний привілей',
    'mysql_not_ip_parce'	=> 'Неправильне значення ip адреси.',
    'mysql_not_edit'	=> 'Спроба редагування не своїх даних',

    'mysql_adddb_wrongformat'	=> 'Будь ласка, використовуйте лише літери a-z та цифри 0-9.',

    'mysql_adddb_emptypass'	=> 'Будь ласка, заповніть пароль.',

    'mysql_adddb_failed_overlimit'	=> 'Перевищено ліміт кількості баз даних. Максимальна кількість баз даних ',

    'mysql_manage_db' => 'База даних MySQL',

    'mysql_select_usermain' => 'Виберіть користувача',
    'mysql_listdb_user' => 'Бази даних',
    'mysql_loaddata_pleasewait' => 'Будь ласка зачекайте',
    'mysql_user_notselect' => 'Ні один користувач не доданий або не вибраний',

    'mysql_run_isok' => 'Працює',
    'mysql_run_isfailed' => 'Зупинено',

    'mysql_intalling' => 'Триває встановлення',	
    'mysql_intalling_successfully' => 'Встановлення завершено',

    'mysql_phpmyadmin_ver' => 'Версія',
    'mysql_phpmyadmin_demo' => '!!! PHPMYADMIN не доступний у демо версії.',
    'mysql_phpmyadmin_demo_2' => 'у звичайній версії він буде доступний.',
    'mysql_message_remove_mysql' => 'При видаленні mysql поштові сервіси та пошта будуть недоступні.',
    'mysql_message_remove_mysql_2' => 'Під час установки або перевстановлення mysql поштові сервіси будуть тимчасово відключені.',
    'mysql_message_stop_mysql' => 'При зупинці mysql поштові сервіси будуть недоступні.',
    'mysql_exit' => 'Відміна',	
    'mysql_continue' => 'Продовжити',
    'mysql_change_password' => 'Змінити пароль',	
    'mysql_short_password' => 'Пароль менше 6 символів',		
    'mysql_succecfully' => 'Виконано',			
    'mysql_disabled_mysqld' => 'Ця дія при вимкненому mysqld сервісі неможлива',			
    'mysql_root_password' => 'Root пароль: ',
    'mysql_root_password_show' => 'Показати',
    'mysql_root_password_hide' => 'Приховати',
    'mysql_confirm_remove_user' => 'Підтвердьте видалення користувача ',
    'mysql_confirm_remove_db' => 'Підтвердьте видалення бази даних ',
    'mysql_control_db' => 'Управління сервером БД',
    'mysql_version' => 'Версія БД:',
    'mysql_control' => 'Керування сервером',
    'mysql_status' => 'Статус БД:',
    'mysql_vers' => 'Версія',
    'mysql_controm_phpmyadmin' => 'Керування phpMyAdmin',
    'mysql_welcome' => 'Ласкаво просимо до',
    'mysql_autorisation' => 'Авторизація',
    'mysql_user' => 'Користувач:',
    'mysql_pass' => 'Пароль:',
    'mysql_input' => 'Увійти',
    'mysql_sintax_error' => 'Синтаксична помилка my.cnf',
    'mysqlPhpMyAdminGetVersion' => 'Перевірити оновлення',
    'mysqlPhpMyAdminAvailNewVersion' => 'Доступна нова версія ',
    'mysqlPhpMyAdminAvailNewVersionNot' => 'Вже встановлена ​​остання версія phpMyAdmin',
    'mysqlPhpMyAdminAvailNewVersionNotIns' => 'Спочатку потрібно встановити',
    'mysqlPhpMyAdminNewVersionInstall' => 'Оновити',
    'mysqlPhpMyAdminUpdateOk' => 'Оновлено успішно ',
    'mysql_download_dump' => 'Завантажити дамп.',
    'mysql_download_dump_error' => 'Помилка завантаження файлу. Підтримувані розширення sql,zip,tgz,tar.gz',
    'mysql_download_dump_error_type' => 'Помилка файлів. Допустимі типи - sql',
    'mysql_download_dump_error_connect' => 'Помилка з`єднання з базою даних',
    'mysql_download_success' => 'Успішно виконано',
    'mysql_download_table_already_exists' => 'У базі даних є таблиці з дампи.',
    'mysql_download_not_db_user' => 'База не належить користувачеві.',
    'mysql_empty_remote_ip' => 'Для відкриття віддаленого доступу повинен бути доданий зовнішній ip',
    'mysql_installonpostg' => 'Встановити/увімкнути Postgresql →',
    'mysql_err_command' => 'Помилка додавання користувача.<br>',
    'mysql_err_command_db' => 'Помилка додавання бази даних.<br>',
    'mysql_empty_user' => 'Немає такого користувача',
    'mysql_empty_db' => 'Немає такої бази даних.',
    'mysql_err_unpacke_arhive' => 'Помилка розпаковування архіву.',
    'mysql_err_param' => 'Помилка параметрів.',
	
);


