<?php

$lang = array(
    'network_tools'		=> 'Мережеві інструменти',
    'network_tools_monit_connect'		=> 'Моніторинг підключень',
    'msg_menu_iptables'		=> 'IP-таблиця',
    'msg_menu_network'		=> 'Мережа',
    'msg_addrules_iptables'	=> 'Додати нове правило:',
    'btn_addrules_iptables'	=> 'Додати правило',
    'btn_save_iptables'		=> 'Зберегти усі зміни',
    'btn_restore_iptables'	=> 'Відновити конфігурацію правил',
    'msg_iptables_add'		=> 'Операцію додавання виконано успішно',
    'msg_iptables_delete'	=> 'Операцію видалення виконано успішно',
    'msg_iptables_save'		=> 'Операцію збереження правил виконано успішно',
    'msg_iptables_restore'	=> 'Операцію відновлення правил виконано успішно',
    'command_iptables_start'	=> 'Старт',
    'command_iptables_stop'	=> 'Стоп',
    'command_iptables_restart'	=> 'Перезапустити',
    'tpl_title_connect'		=> 'Загальна кількість з`єднань:',
    'tpl_title_connect_syn'	=> 'Усього з`єднань у стані SYN_RECEIVED:',
    'tpl_title_connect_port'	=> 'Усього з`єднань на обраний порт:',
    'tpl_title_net_status'	=> 'Статус останньої операції: ',
    'tpl_title_block_size'	=> 'Заблокувати всі IP, кількість з`єднань яких більше:',
    'tpl_btn_list_show_hide'	=> 'Показати/приховати список IP',
    'tpl_btn_list_hideact'	=> 'Приховати список IP',
    'tpl_netstat_iptables_link'	=> 'Заблокувати IP через IP-таблицю',
    'tpl_btn_block_size'	=> 'Запустити вручну',
    'msg_netstat_status_null'	=> 'Нема чого блокувати',
    'msg_netstat_block_onlyip'	=> ' - заблоковано вказаний IP',
    'msg_netstat_block_size'	=> ' - IP адрес заблоковано',
    'btn_run_check_start'	=> 'Запустити скрипт',
    'btn_run_check_stop'	=> 'Зупинити скрипт',
    'msg_run_check_stop'	=> 'Не працює',
    'btn_stop_start_log'	=> 'Відкрити/Закрити журнал',
    'btn_update_log'		=> 'Оновити інформацію журналу',
    'msg_start_script_info'	=> 'Або запустити скрипт із періодом (у секундах)',
    'msg_checked_log_value'	=> 'Увімкнути логування',
    'msg_run_script_status'	=> 'Статус скрипта: ',
    'msg_run_script_start'	=> 'працює',
    'msg_run_script_stop'	=> 'не працює',
    'msg_info_first_line'	=> 'інформація про роботу',
    'networktools_allports'	=> 'Всі',
    'networktools_rule_wrongformat'	=> 'Невірний формат правила',
    'networktools_th_name'	=> 'Назва',
    'networktools_th_connect'	=> 'Кількість <br/>з`єднань',
    'networktools_th_manage'	=> 'Управління',
    'networktools_delete_rules'	=> 'Видалити правило',
    'networktools_get_list_ip'	=> 'Показати список IP',
    'networktools_close_journal'	=> 'Закрити журнал',
    'networktools_period_works_script'	=> 'Період работи скрипта',
    'networktools_start_one'	=> 'Запустити одноразово',
    'networktools_start_timer'	=> 'Запустити по таймеру',
    'networktools_open_journal'	=> 'Відкрити журнал',
    'networktools_num_connect'	=> 'Кількість з`єднань',
    'networktools_not_connect'	=> 'Немає з`єднань',
    'networktools_port'	=> 'Порт',
    'networktools_confirm_lock_ip'	=> 'Підтвердьте блокування IP',
    'networktools_confirm_lock_ip_2'	=> 'заблокувати підмережу x.x.x.x/24',
    'networktools_noactiveconnsuchtype'=>'Немає активних з`єднань даного типу',

);


