<?php
$lang = array(
    'packet_manager2'	=> 'Пакетний менеджер',
    'package_installed'		=> 'Встановлено',
    'package_working'		=> 'Працює',
    'package_control'		=> 'Керування',	
    'package_start'			=> 'Старт',
    'package_stop'			=> 'Стоп',
    'package_restart'		=> 'Перезавантажити',
    'package_kill'			=> 'Примусово зупинити',
    'package_autoload'		=> 'Автозавантаження',	
    'package_reinstall'		=> 'Перевстановити',
    'package_delete'		=> 'Видалити',	
    'package_setting'		=> 'Налаштувати',	
    'package_repare_standart_conf'		=> 'Відновити стандартні установки',	
    'package_error_parameters'		=> 'Помилка параметрів',	
    'package_error_parameters_config'		=> 'Ця команда не знайдена у файлі конфігурації',	
    'package_error_comand_os'		=> 'Не знайдено команду для даної операційної системи',	
    'package_successfully'		=> 'Успішно виконано.',	
    'package_not_file_config'		=> 'Немає конфігураційного файлу',	
    'package_editable_conf'		=> 'Редагувати ',	
    'package_manager_for_user'		=> 'Для користувачів',	
    'package_manager_for_expert'		=> 'Для експертів',	
    'package_manager_save'		=> 'Зберегти',	
    'package_error_config'		=> 'Помилка конфігурації',	
    'package_not_file_repair_conf'		=> 'Файл відновлення не знайдено.',	
    'package_confirm'		=> 'Підтвердіть цю дію',	
    'package_install_version'		=> 'Встановлена ​​версія ',	
    'package_packet'		=> 'Пакет',
    'roundAvailNewVersionNot' => 'Вже встановлена ​​остання версія Roundcube',
    'packet_manager_please_wait_password' => 'Виконується зміна пароля mysql. Будь ласка зачекайте.',
    'packet_manager_please_wait_save' => 'Будь ласка зачекайте. Триває збереження конфігу.',
	
);
