<?php

$lang = array(
    'packet_manager'	=> 'Пакетний менеджер',
    'packet_manager_title2' => 'Менеджер додатків',
    'msg_package_status'	=> 'Не працює',
    'msg_package_err_login'	=> 'У вас недостатньо прав для заходу на цю сторінку',

    'tpl_package_del'			=> 'Видалити',
    'tpl_package_save'			=> 'Зберегти',
    'tpl_package_installed'		=> 'Встановлено',
    'tpl_package_working'		=> 'Працює',
    'tpl_package_log_show'		=> 'Дивитися лог останньої установки/видалення',
    'tpl_package_go_process'		=> 'Триває процес... ',
    'tpl_package_install'		=> 'Встановити',
    'tpl_package_delete'		=> 'Видалити',
    'tpl_package_control'		=> 'Керування',
    'tpl_package_start'			=> 'Старт',
    'tpl_package_stop'			=> 'Стоп',
    'tpl_package_restart'		=> 'Перезапустити',
    'tpl_package_kill'			=> 'Примусово зупинити',
    'tpl_package_autoload'		=> 'Автозавантаження',

    'js_package_delete'		=> 'Виконуємо видалення...',
    'packet_manager_succecfully'		=> 'Успішно змінено',

    'packet_manager_brainysql'	=> 'Сервер баз даних BrainySQL',
    'packet_manager_memcached'	=> 'Кешування пам`яті',
    'packet_manager_ffmpeg'	=> 'Powerful UNIX VIDEO ENCODER',
    'packet_manager_imagemagick'	=> 'Інструмент для роботи із зображеннями',
    'packet_manager_httpry'	=> 'Мережевий аналізатор HTTP-трафіку',
    'packet_manager_certbot'	=> 'Скрипт для роботи із Let’s Encrypt сертифікатами',
    'packet_manager_megacli'	=> 'Додаток для відображення інформації про RAID',
    'packet_manager_iotop'	=> 'Аналіз навантаження на дискову підсистему',
    'packet_manager_atop'	=> 'Інтерактивний монітор продуктивності',
    'packet_manager_iftop'	=> 'Статистика мережного інтерфейсу',
    'packet_manager_logrotate'	=> 'Утиліта автоматичного стиснення, видалення журналів системи',
    'packet_manager_smartmon'	=> 'Утиліта моніторингу стану накопичувача',
    'packet_manager_php52'	=> 'php 5.2',
    'packet_manager_php53'	=> 'php 5.3',
    'packet_manager_php54'	=> 'php 5.4',
    'packet_manager_php55'	=> 'php 5.5',
    'packet_manager_php56'	=> 'php 5.6',
    'packet_manager_php70'	=> 'php 7.0',
    'packet_manager_php71'	=> 'php 7.1',
    'packet_manager_php72'	=> 'php 7.2',
    'packet_manager_git'	=> 'Розподілена система управління версіями',
    'packet_manager_shellinabox'	=> 'Браузерний shell клієнт',
    'packet_manager_postgresql'	=> 'База даних postgresql',
    'packet_manager_phppgadmin'	=> 'Адміністрування сервера PostgreSQL',
    'packet_manager_redis'      => 'База даних для сховища ключів',
    'packet_manager_openvpn'      => 'OpenVPN транспорт',
    'packet_manager_lognotexist'=>'Лога не існує',
);


