<?php

$lang = array(
    //client
    'tpl_c_serv_control_select_ip' => 'Вибір IP',
    'tpl_c_serv_control_select_php' => 'Вибір версії PHP/NodeJS',
    'tpl_c_serv_control_all_sites' => 'Всі сайти',
    'tpl_c_serv_control_bridge' => 'Міст',
    'tpl_c_serv_control_ver_php' => 'Версія PHP',
    'tpl_c_serv_control_control' => 'Керування',

    //server
    'tpl_s_serv_control_php' => 'PHP',
    'tpl_s_serv_control_delete' => 'Видалення',
    'tpl_s_serv_control_reinstall' => 'Перевстановити',
    'tpl_s_serv_control_status' => 'Статус сервера',
    'tpl_s_serv_control_more' => 'Детальніше',
    'tpl_s_serv_control_hide' => 'Приховати',
    'tpl_s_serv_control_choose_bridge' => 'Можливість вибрати міст',
    'tpl_s_serv_control_yes' => 'Так',
    'tpl_s_serv_control_no' => 'Ні',
    'tpl_s_serv_control_available_bridges' => 'Доступні мости',
    'tpl_s_serv_control_default_bridge' => 'Міст за замовчуванням',
    'tpl_s_serv_control_choose_php' => 'Можливість вибрати версію PHP',
    'tpl_s_serv_control_available_php' => 'Доступні версії PHP',
    'tpl_s_serv_control_default_php' => 'Версія PHP за замовчуванням',
    'tpl_s_serv_control_apply' => 'Застосувати',
    'tpl_s_serv_control_save_config' => 'Зберегти поточну конфігурацію',
    'tpl_s_serv_control_load_config' => 'Завантажити поточну конфігурацію',
    'tpl_s_serv_control_cancel' => 'Відміна',
    'tpl_s_serv_control_params_config' => 'Параметри збереженої конфігурації',

    'tpl_s_serv_control_open_bridge' => 'Відкриті мости',
    'tpl_s_serv_control_open_php' => 'Відкриті версії PHP',
    'tpl_s_serv_control_select_bridge' => 'Можливість вибрати міст',
    'tpl_s_serv_control_select_php' => 'Можливість вибрати PHP',

    'tpl_s_serv_control_delete_conf' => 'Видалити збережену конфігурацію',
    'tpl_s_serv_control_action' => 'Дія',
    'tpl_s_serv_control_edit_php_ini' => 'Редагування основних опцій php.ini',
    'tpl_s_serv_control_edit_beginners' => 'Для початківців',
    'tpl_s_serv_control_edit_experts' => 'Для експертів',
    'tpl_s_serv_control_save' => 'Зберегти',
    'tpl_s_serv_control_ver_select' => 'Вибір версії',

    'tpl_c_serv_control_control_fpm' => 'Керування fpm',
    'tpl_c_serv_control_start' => 'Старт',
    'tpl_c_serv_control_stop' => 'Стоп',
    'tpl_c_serv_control_restart' => 'Перезавантажити',
    'tpl_c_serv_control_force_restart' => 'Перезавантажити примусово',

    'tpl_c_serv_control_client_options' => 'Клієнтські опції',

    'tpl_c_serv_control_connect_php_php' => 'Підключити PHP як mod_php',
    'tpl_c_serv_control_connect_php_cgi' => 'Підключити PHP як cgi',
    'tpl_c_serv_control_connect_php_fcgi' => 'Підключити PHP як fcgi',
    'tpl_c_serv_control_connect_php_suphp' => 'Підключити PHP як suphp',
    'tpl_c_serv_control_connect_php_ruid2' => 'Підключити PHP як ruid2',
    'tpl_c_serv_control_connect_php_fpm' => 'Підключити PHP як fpm',
    'tpl_c_serv_control_connection' => 'Підключення',
    'tpl_c_serv_control_additions' => 'Доповнення',
    'tpl_c_serv_control_additions_connection' => 'Підключення доповнень',

    'tpl_s_serv_control_name' => 'Ім`я',
    'tpl_s_serv_control_stat' => 'Статус',
    'tpl_s_serv_control_install' => 'Встановити',
    'tpl_s_serv_control_del' => 'Видалити',
    'tpl_s_serv_control_hookup' => 'Підключити',
    'tpl_s_serv_control_select_all' => 'Вибрати все',
    'tpl_s_serv_control_cancel_all' => 'Деактивувати все',
    'tpl_s_serv_control_connected' => 'Підключено',


    'tpl_s_serv_control_save_config_php' => 'Зберегти поточну конфігурацію php',
    'tpl_s_serv_control_load_config_php' => 'Завантажити поточну конфігурацію php',
    'tpl_s_serv_control_version_selection' => 'Вибір версії',

    'tpl_s_serv_control_control_fpm' => 'Керування fpm',

    'tpl_s_serv_control_command_already_done' => 'Команда вже була успішно виконана',

    'tpl_s_serv_control_isntall_megapack' => 'Встановлення готових зв`язків',
    'tpl_s_serv_control_isntall_megapack_select_webserver' => 'Виберіть веб-сервер',

    'tpl_s_serv_control_isntall_megapack_select_php' => 'Виберіть версію php',
    'server_control_mess_repo_update' => 'Список розширень php оновлюєтся',
    'server_control_mess_repo_update_ok' => 'Список розширень php успішно оновлено',

    'server_control_n' => 'Віртхости перебудовані успішно.',
    'server_control_n_f_u' => 'Немає даних для користувача',
    'server_control_n_f_a' => 'Аліас поля заповнені неправильно. Будь ласка, використовуйте лише літери, цифри, тире та крапки. ',
    'server_control_n_f_e' => 'Аліас вже існує в основному домені',
    'server_control_are' => 'Аліас вже існує',
    'server_control_alias_alredy_domain' => 'Аліас прописаний у полі домен.',
    'server_control_c' => 'Dir field completed incorrectly. Please use only letters, numbers, dash and slash.',
    'server_control_d_f' => 'Domain field completed incorrectly. Please use only letters, numbers, dash and dot.',
    'server_control_d_c' => 'Dir field should be completed',
    'server_control_dom_c' => 'Domain field should be completed',
    'server_control_dom_a_f' => 'Alias field completed incorrectly. Please use only letters, numbers, space, semicolon, coma, dash and dot.',
    'server_control_dom_a_a_e' => 'Alias already exists',
    'server_control_dom_d_f_c' => 'Поля директорії неправильно заповнені. Будь ласка, використовуйте тільки букви, цифри, тире та косу лінію.',
    'server_control_dom_d_f_i' => 'Поле домен заповнено неправильно. Будь ласка, використовуйте тільки букви, цифри, тире та крапку.',
    'server_control_dom_d_f_s' => 'Поле директорія має бути заповненим',
    'server_control_dom_d_f_s_c' => 'Поле домен має бути заповненим',
    'server_control_i_s' => 'Встановлення завершено успішно',
    'server_control_i_ns' => 'Установка завершена з помилкою',
    'server_control_i' => 'Триває встановлення',
    'server_control_s_a' => 'Налаштування застосовані',
    'server_control_i_d' => 'Триває видалення',
    'server_control_d_s' => 'Видалення завершено успішно',
    'server_control_d_a' => 'Видалення завершено з помилкою',
    'server_control_c_o' => 'Конфігурація опцій збережена',
    'server_control_c_d' => 'Збережена конфігурація видалена',
    'server_control_o' => 'Обробка',
    'server_control_i_i' => 'Підключення...',
    'server_control_r_h' => 'Йде процес розбудови віртуальних хостів.',
    'server_control_z_v' => 'Запит виконуєтся',
    'server_control_r_o' => 'Редагування основних опцій php.ini',
    'server_control_f_u' => 'Для Користувачів',
    'server_control_f_e' => 'Для експертів',
    'server_control_s_v' => 'Вибір версії',
    'server_control_w_s' => 'Веб-сервер',
    'server_control_a_2' => 'apache2.2',
    'server_control_a_24' => 'apache2.4',
    'server_control_ng' => 'nginx',
    'server_control_a_n' => 'apache2.2+nginx',
    'server_control_a24_n' => 'apache2.4+nginx',
    'server_control_ko' => 'Клієнтські опції',
    'server_control_start' => 'start',
    'server_control_stop' => 'stop',
    'server_control_restart' => 'restart',
    'server_control_frestart' => 'force restart',
    'server_control_m_f' => 'Керування fpm',
    'server_control_s_w' => 'Вибір версії',
    'server_control_save' => 'Зберегти',
    'server_control_r_i' => 'Перевстановити',
    'server_control_m_d' => 'Міст за замовчуванням:',
    'server_control_v_php' => 'Версія php за замовчуванням:',
    'server_control_prim' => 'Застосувати',
    'server_control_s_m' => 'Можливість вибрати міст:',
    'server_control_y' => 'yes',
    'server_control_no' => 'no',
    'server_control_sv_php' => 'Можливість вибрати версію php:',
    'server_control_d_m' => 'Доступні мости:',
    'server_control_d_v_php' => 'Доступні версії php:',
    'server_control_i_php_m' => 'Підключити php як mod_php',
    'server_control_i_php_c' => 'Підключити php як cgi',
    'server_control_i_php_f' => 'Підключити php як fcgi',
    'server_control_i_php_su' => 'Підключити php як suphp',
    'server_control_i_php_ruid' => 'Підключити php як mod_ruid2',
    'server_control_i_php_fpm' => 'Підключити php як fpm',
    'server_control_u_cache' => 'Оновити список php розширень',
    'server_control_dop' => 'Доповнення',
    'server_control_name' => 'Ім`я',
    'server_control_status' => 'Статус',
    'server_control_install' => 'Встановити',
    'server_control_del' => 'Видалити',
    'server_control_sel_all' => 'Вибрати все',
    'server_control_podcl' => 'Підключити',
    'server_control_ins' => 'Встановлено',
    'server_control_pod' => 'Підключено',
    'server_control_s_t_c' => 'Зберегти поточну конфігурацію php',
    'server_control_l_t_c' => 'Завантажити збережену конфігурацію php',
    'server_control_i_php7' => 'Підключення доповнень php 7.0',
    'server_control_mark_all' => 'Відзначити все',
    'server_control_deactivate_all' => 'Деактивувати все',
    'server_control_to_applay' => 'Застосувати',
    'server_control_supl_php' => 'Доповнення php 7.0',
    'server_control_supl56' => 'Підключення доповнень php 5.6',
    'server_control_supl_php56' => 'Доповнення php 5.6',
    'server_control_proceccing' => 'Обробка',
    'server_control_supl55' => 'Доповнення php 5.5',
    'server_control_supl54' => 'Підключення доповнень php 5.4',
    'server_control_supl_54' => 'Доповнення php 5.4',
    'server_control_supl53' => 'Підключення доповнень php 5.3',
    'server_control_supl_53' => 'Доповнення php 5.3',
    'server_control_supl52' => 'Підключення доповнень php 5.2',
    'server_control_supl_52' => 'Доповнення php 5.2',
    'server_control_installing' => 'Триває встановлення',
    'server_control_installing_s' => 'Встановлення завершено успішно',
    'server_control_installing_e' => 'Встановлення завершено з помилкою',
    'server_control_d_s_e' => 'Домен успішно відредаговано',
    'server_control_s_added' => 'Домен був успішно доданий',
    'server_control_d_already' => 'Домен уже існує',
    'server_control_not_start' => 'There is no server-status module for this type of webserver',
    'server_control_s_ok' => 'Зупинка',
    'server_control_start_ok' => 'Запуск',
    'server_control_domain_sus_delete' => 'Домен успішно вилучено',
    'server_control_not_version_aiab' => 'Зміна версії недоступна',
    'server_control_ability_bridg' => 'Можливість вибрати міст:',
    'server_control_ability_php' => 'Можливість вибрати php:',
    'server_control_key_loaded' => 'Ключ завантажений',
    'server_control_csr_created' => 'CSR створено',
    'server_control_error' => 'Error',
    'server_control_error_read_file' => 'Error reading file',
    'server_control_key_created' => 'Key created',
    'server_control_edit' => 'Редагувати',
    'server_control_select_bridg' => 'Вибір моста:',
    'server_control_not_domain' => 'Домен не знайдено.',
    'server_control_not_paf_domain' => 'Поле домен має бути заповненим',
    'server_control_is_not_ip' => 'Ця IP адреса вам не належить',
    'server_control_error_dir' => 'Помилка при зміні директорії каталогу',
    'server_control_not_bridg' => 'Такого моста не існує. Доступні мости - ',
    'server_control_not_php' => 'Такої версії php немає. Доступні версії - ',
    'server_control_phpvers_default' => 'Домен успішно відредаговано. Php за замовчуванням - ',
    'server_control_phpvers_default1' => 'Домен успішно доданий. Php за замовчуванням - ',
    'server_control_all_version' => '. Доступні версії - ',
    'server_control_bridg_default' => 'Домен успішно відредаговано. Міст за замовчуванням - ',
    'server_control_bridg_default1' => 'Домен успішно доданий. Міст за замовчуванням - ',
    'server_control_not_root' => 'У вас не достатньо прав. Заберіть поле user_edit',
    'server_control_list_domain' => 'Отримано список доменів.',
    'server_control_email_exist' => 'На цьому домені є поштові облікові записи. Спочатку видаліть їх.',

    'server_control_error_user' => 'Помилка параметрів',
    'server_control_err_ip' => 'Помилка в адресах IP. Можливо, їх не визначено.',

    'server_control_overlimit_domains' => 'Досягнуто ліміту на кількість сайтів. Максимальна кількість сайтів',

    'server_control_overlimit_dnz_zones' => 'Досягнуто ліміту кількості DNS зон. Максимальна кількість зон DNS ',
    'server_control_alias_alr_exist' => 'Аліас вже існує.',

    'server_control_label_sel_admin' => 'Ім`я користувача',
    'server_control_please_wait' => 'Будь ласка зачекайте',
    'server_control_pleas_wait_adding' => 'Зачекайте, йде додавання',

    'server_control_no_site_added' => 'Сайти ще не додані',
    'server_control_user_notselect' => 'Зазначеному критерію пошуку доменів немає',
    'server_control_seluserplease' => 'Будь ласка, виберіть користувача',
    'server_control_selversion' => 'Вибір версії',
    'server_control_fpm_restart_all' => 'Виконати на все FPM',
    'server_control_viewprogress' => 'Переглянути процес',
    'server_control_stopprogress' => 'Зупинити встановлення',
    'server_control_processrun' => 'Виконується встановлення...',
    'server_control_warning' => 'Зупинка процесу встановлення php може призвести до некоректної роботи php. Будь ласка, підтвердьте зупинку процесу.',
    'server_control_warning_yesstop' => 'Зупинити',
    'server_control_warning_nocont' => 'Продовжити',
    'server_control_pleaseselectphp' => 'Виберіть версію php',
    'server_control_pleaseselectphp_all_install' => 'Усі версії php вже встановлені',
    'server_control_pleaseselectphp_reinstall' => 'Виберіть версію php для переустановки',
    'server_control_pleaseselectphp_all_reinstall' => 'Жодна версія php ще не встановлена',

    'server_control_configsaveok' => 'Налаштування застосовані',
    'server_control_warning_mega' => 'Припинення процесу встановлення зв`язки може призвести до некоректної роботи php та вебсервера. Будь ласка, підтвердьте зупинку процесу.',
    'server_control_extensionphptitletable' => 'Розширення PHP',
    'server_control_sel_bridge' => 'Вибір моста:',
    'server_control_demo_message' => 'Вибачте, в демо версії цю дію вимкнено.',
    'server_control_nothingtodel' => 'Виберіть, що потрібно видалити.',
    'server_control_nothingtodel_notinstall' => 'Нічого не встановлено. Будь ласка, установіть необхідний набір зв`язок на вкладці Веб-сервер',

    'server_control_fpm_startok' => 'Успішний запуск',
    'server_control_fpm_ok_mess' => 'Успішний',
    'server_control_star' => 'Символ * доступний тільки в Аліасах',

    'server_control_confirmdeldom' => 'Підтвердьте видалення домену',
    'server_control_confirmdeldom_withfiles' => 'Видалити файли та папку домену',

    'server_control_deldomadeny' => 'Ви не маєте права на видалення вказаного домену.',

    'server_control_mod_modsec' => 'Керування ModSecurity',
    'server_control_mod_modsec_check_label' => 'Активувати',
    'server_control_defaulthint_stat_modsec' => 'Статус mod_security не було конфігуровано',

    'server_control_mod_modsec_stat_change' => 'Статус ModSecurity змінено',
    'server_control_mod_modsec_stat_off' => 'ModSecurity вимкнено. Будь ласка, зверніться до адміністратора сервера.',

    'server_controlAliasHint' => 'Поле необов`язкове для введення. Для введення кількох аліасів розділіть пробілом, переносом рядка, комою або ;',
    'server_statLogDomains' => 'Статус логування доменів',
    'server_control_seluserLogs' => 'Виберіть користувача',
    'server_control_LogDomain' => 'Домен',
    'server_control_LogDomainAccess' => 'Логи доступу',
    'server_control_LogDomainError' => 'Логи помилок',
    'server_control_LogDomainDomainNotExist' => 'Користувач не має доменів',
    'server_control_LogDomainDomainWrongUsername' => 'Неправильне ім`я користувача',
    'server_control_LogDomainDomainSetOk' => 'Статус логування змінено успішно',
    'server_control_MenuStatusLog' => 'Управління статусом логування',
    'server_control_hintLogAccess' => 'Статус логування access_log /etc/httpd/vhost_logs/domain_access и/или /etc/nginx/vhost_logs/domain_access',
    'server_control_hintLogError' => 'Статус логування error_log /etc/httpd/vhost_logs/domain_error и/или /etc/nginx/vhost_logs/domain_error',
    'server_control_logs' => 'Логи',
    "server_tcp_socket_err_create" => "Помилка створення сокету",
    "server_tcp_socket_err_conn" => "Помилка з`єднання сокету",
    "server_showAll" => "Показати все",
    "server_listDomColUser" => "Користувач",
    "server_hintDenyEditBridgeRoot" => "Редагування мосту недоступне, тому що для користувача включений jailphp. Відключити jailphp можна <a target=``_blank`` href=``index.php?do=hostacc&subaction=jail``>тут</a>",
    'server_control_captionDomain' => 'Домен',
    'server_control_captionDomainHolder' => 'Введіть домен або аліас',
    'server_controlAllVersionPhps' => 'Всі версії php',
    'server_controlAllUsers' => 'Всі користувачі',
    'server_controlFilterDoms' => 'Пошук: ',
    'server_controlpath_config' => 'Шлях до файлу конфігурації',
    'server_control_dont_user_jail' => 'Вибраний користувач не розміщений в Jail PHP',
    'server_control_dont_file_config' => 'Файл конфігурації php.ini, не знайдено.',
    'server_control_extensions_php_user_jail' => 'Розширення для користувачів jail',
    'server_control_whait_reinstall_php' => 'Очікуйте триває встановлення php',
    'server_control_whait_delete_php' => 'Очікуйте триває видалення php',
    'server_control_whait_reinstall_webserver' => 'Очікуйте триває встановлення зв`язки',
    'server_control_error_directive' => 'Помилка введення значення директиви ',
    'server_control_error_paramert' => 'Помилка параметрів.',
    'server_control_error_pm_start_servers' => 'pm.start_servers має бути не менше pm.min_spare_servers і не більше pm.max_spare_server',
    'server_control_error_pm_start_servers2' => 'pm.min_spare_servers має бути не більше pm.max_spare_server',
    'server_control_error_rm_sites' => 'У директорії сайту знаходяться інші сайти хостаккаунта.',
    'server_control_warning_delete' => 'Зупинення процесу Видалення php або вебсервера може призвести до некоректної роботи php і вебсервера. Будь ласка, підтвердіть зупинку процесу.',
    'server_control_stopprogress_delete' => 'Зупинити видалення',
    'server_forbidden_add_subdomain' => 'Заборонити додавання субдоменів іншим хост-акаунтам',
    'server_forbidden_add_subdomain_message' => 'Помилка додавання субдомену, корінний домен використовує інший хост-аккаунт',
    'server_control_error_aliases' => 'Аліаси заповнені неправильно. Поле аліас має містити валідний домен.',
    'server_forbidden_add_subdomainHintEdit' => 'У разі включення заборони дія починається з моменту встановлення – з доданими раніше субдоменами зміни виконані не будуть',
    'server_control_erroractmpm'=>'Сталася помилка під час активації нового MPM ',
    'server_control_setupdefaultmpm'=>' встановлений за замовчуванням.',
    'server_control_applysuccesscurap'=>' успішно застосований для поточного Apache.',
    'server_control_adddomain'=>'Додати сайт',
    'server_control_configfpm_phpcgi'=>'Налаштування параметрів FPM пулів для PHP CGI',
    'server_control_areaapplyvalues'=>'Область застосування цих значень - всі сайти вказаного хост-акаунта.',
    'server_control_bridgerules'=>'Міст mod_php працює лише з MPM Prefork. Протокол http2 працює лише з MPM Worker та Event.',
    'server_control_usempm'=>'Використовувати модуль MPM Apache',
    'server_defaultpage_title'=>'Сторінка за замовчуванням',
    'server_defaultpage_managebrainy'=>'Цей сервер керується панеллю керування BrainyCP. Якщо ви очікуєте побачити сайт, то, можливо, ви:',
    'server_defaultpage_notadddomain'=>'не додали доменне ім`я до розділу Сайти;',
    'server_defaultpage_notclearcache'=>'не очистили кеш вашого браузера;',
    'server_defaultpage_wrongip'=>'прив`язали домен до невірного айпу адресою.',
    'server_defaultpage_yourhostingpanel'=>'Панель керування Вашим хостингом — ',
    'server_sitecreateok'=>'Ваш сайт був успішно створений',
    'server_domaincreateok'=>'Ваш домен успішно створено',
    'server_replacefielindextostartwork'=>'Замініть файл index.html у папці домену на свої файли і ваш сайт почне працювати.',
    'server_sitesuspmessage'=>'Ваш сайт на обліковому записі',
    'server_seitesuspmess2'=>'був заблокований',
    'server_panelcaption'=>'Панель управління',
    'server_locksiteextend'=>'Ви бачите цю сторінку, оскільки Ваш сайт заблоковано. Зверніться до адміністратора сервера за детальною інформацією.',
    'server_loginotheruser'=>'Увійти під іншим користувачем',
    'server_panelsuspmessage'=>'Ваш обліковий запис',
    'server_lockpanelextend'=>'Ви бачите цю сторінку, оскільки Ваш обліковий запис було заблоковано. Зверніться до адміністратора сервера за детальною інформацією.',

    'js_nodejs_action' => 'NodeJS додаток на цьому порту буде перезапущено',
    'web_nodejs_app_ok' => 'Програма NodeJS була успішно перезапущена, порт програми: ',
    'web_nodejs_app_err' => 'Відбулася помилка при перезапуску NodeJS програми з портом: ',
    'web_nodejs_app_no' => 'Не вдалося виявити програму NodeJS з портом ',
    'server_defaultpage_emptycert' => 'Немає сертифіката під час використання протоколу https.',
    'server_control_confirmdel_dns_zone' => 'Видалити dns зону',

);


