<?php

$lang = array(
    'speedtest' => 'Швидкість каналу сервера',
	'speedtest_header'	=> 'Швидкість каналу сервера',
	'speedtest_check_btn'	=> 'Перевірити швидкість до цієї точки',
    'speedtest_choose_server'=>'Виберіть сервер',
    'speedtest_check_speed'=>'Перевірка швидкості',
    'closest_server'=>'Найближчий сервер',
    'Kiev' => 'Київ',
    'Ukraine' => 'Україна',
    'Moscow' => 'Москва',
    'Russian_Federation' => 'Росія',
    'Russian Federation' => 'Росія',
    'Petersburg' => 'Санкт-Петербург',
    'Chelyabinsk' => 'Челябінськ',
    'Vladivostok' => 'Владивосток',
    'Vilnius' => 'Вільнюс',
    'Lithuania' => 'Литва',
    'Riga' => 'Рига',
    'Latvia' => 'Латвія',
    'Tallinn' => 'Таллінн',
    'Estonia' => 'Естонія',
    'Prague' => 'Прага',
    'Czech_Republic' => 'Чехія',
    'Kazakhstan' => 'Казахстан',
    'Astana' => 'Астана',
    'Minsk' => 'Мінськ',
    'Belarus' => 'Білорусь',
    'Tashkent' => 'Ташкент',
    'Uzbekistan' => 'Узбекистан',
    'Paris' => 'Париж',
    'France' => 'Франція',
    'Rome' => 'Рим',
    'Italy' => 'Італія',
    'London' => 'Лондон',
    'Great_Britain' => 'Великобританія',
    'Amsterdam' => 'Амстердам',
    'Netherlands' => 'Нідерланди',
    'Toronto' => 'Торонто',
    'Canada' => 'Канада',
    'Berlin' => 'Берлін',
    'Germany' => 'Німеччина',
    'Dubai' => 'Дубаї',
    'United_Arab_Emirates' => 'ОАЕ',
    'Beijing' => 'Пекін',
    'China' => 'Китай',
    'New_Delhi' => 'Нью-Делі',
    'India' => 'Індія',
    'Washington' => 'Вашингтон',
    'United_States' => 'США',
    'New_York_City' => 'Нью-Йорк',
    'Poland' => 'Польша',
    'Moldova' => 'Молдова',
    'Romania' => 'Румунія',
    'Slovakia' => 'Словаччина',
    'Hungary' => 'Угорщина',
    'Bulgaria' => 'Болгарія',
    'Czech Republic' => 'Чехія',
    'Serbia' => 'Сербія',
    'Kharkiv' => 'Харків',
    'Lviv' => 'Львів',
    'Odessa' => 'Одеса',
    'Belgorod' => 'Білгород',
    'Rostov-on-Don' => 'Ростов-на-Дону',
    'Lublin' => 'Люблін',
    'Wroclaw' => 'Вроцлав',
    'Poznan' => 'Познань',
    'Krakow' => 'Краків',

	

);

