<?php

$lang = array(
    'web_statistics'        => 'Веб-статистика',
    'web_cron_warning'        => 'Увага!CROD не працює на сервері.Модуль може працювати неправильно.Встановіть і запустити CROD для правильної роботи.',

    'tpl_site_no_static'        => 'Cтатистика не доступна',
    'tpl_msg_site_name_list'        => 'Список обробки доменів',
    'tpl_webstat_options_alluser'    => 'Установки для всіх існуючих користувачів: ',
    'tpl_webstat_run_sites_webalizer'    => 'Обробка для всіх сайтів webalizer:',
    'tpl_webstat_webalizer_on'        => 'Увімкнути',
    'tpl_webstat_webalizer_off'        => 'Вимкнений',
    'tpl_webstat_webalizer_default'    => 'За замовчуванням',
    'tpl_webstat_run_sites_awstat'    => 'Обработка для всех сайтов awstats:',
    'tpl_webstat_awstat_on'        => 'Увімкнути',
    'tpl_webstat_awstat_off'        => 'Вимкнений',
    'tpl_webstat_awstat_default'    => 'За замовчуванням',
    'tpl_webstat_on_new_webanalizer'    => 'Увімкнути обробку для всіх нових сайтів webalizer',
    'tpl_webstat_on_new_awstat'        => 'Увімкнути обробку всіх нових сайтів AWSTATS',
    'tpl_webstat_apply'            => 'Застосовувати',
    'tpl_webstat_options_select_user'    => 'Установки для вибраного користувача',
    'tpl_webstat_select_user'        => 'Виберіть користувача',
    'tpl_webstat_on_newsite_webanaliz'    => 'Увімкнути обробку для всіх нових сайтів webalizer',
    'tpl_webstat_on_newsite_awstat'    => 'Увімкнути обробку для всіх нових сайтів AWSTATs',
    'tpl_webstat_on_control_webanaliz'    => 'Дозволити керування Webalizer',
    'tpl_webstat_on_control_newsite_awstat'    => 'Дозволити управління Awstats',
    'tpl_webstat_save_configure'    => 'зберегти зміни',
    'tpl_webstat_allnew_user'    => 'Встановіть для всіх нових користувачів:',
    'tpl_webstat_allnew_user_web_oncontrol'    => 'Дозволити керування webalizer.',
    'tpl_webstat_allnew_user_awstat_oncontrol'    => 'Дозволити управління Awstats',
    'tpl_webstat_allnew_user_web_onsites'    => 'Увімкнути обробку веб-сайту для всіх сайтів',
    'tpl_webstat_allnew_user_awstat_onsites'    => 'Увімкнути обробку AWSTATS для всіх сайтів',
    'tpl_webstat_list_webanalizer'    => 'webalizer',
    'tpl_webstat_list_awstats'        => 'Awstats',
    'tpl_webstat_list_all'        => 'вибрати все',
    'tpl_webstat_list_return'        => 'Повернутися до списку сайтів',

    'msg_status_process_admin_ok'    => 'Нові парметери зберігаються',
    'msg_status_process_user_ok'    => 'Ваші параметри успішно зберігаються.',
    'msg_status_process_user_err'    => 'Файл з параметрами відсутній або пошкоджений',
    'webstat_view_webalizer'         => 'Переглянути webalizer.',
    'webstat_view_awstats'        => 'Погляд Awstats',
    'webstat_save_configure'        => 'Нові значення зберігаються',

    'js_webstat_save_configure'        => 'Нові значення зберігаються',
    'web_statistics_request_failed'        => 'Request failed',
    'web_statistics_script_error'        => 'Script error:',
    'web_statistics_nosites'        => 'Користувач не має додаткових сайтів.',
    'web_statistics_no_static_webalizer'        => 'статистика Webalizer НеДоступна',
    'web_statistics_no_static_awstats'        => 'Статистика Awstats не доступні',
    'web_statistics_period_run'        => 'Оновлення відбувається 1 раз ',
    'web_statistics_period_run_hour'        => 'час',
    'web_statistics_period_run_min'        => 'Хв.',
    'web_statistics_period_conf'        => 'Налаштування',
    'web_statistics_save'        => 'Зберегти',
    'web_statistics_remove_update'        => 'Оновлення вимкнено',
    'web_statistics_update'        => 'Оновити кожен',



);
